const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const langPack={
 zh:{enter:'中文进入',enEnter:'English',home:'首页',tower:'声之塔',map:'星盘',voice:'声乐',life:'生活',explore:'探索',math:'数理',library:'资料',short:'少字',motion:'低动效',back:'回首页',search:'搜索知识星辰…',open:'打开动画',source:'打开来源',learn:'展开学习',complete:'点亮这一关',reset:'重置进度',title:'Musicalife',sub:'一个探索音乐趣味的可视化平台',poem:'像乘坐一只知识的小船，穿过声波、星光、身体、语言和世界。音乐不是只有声音，它是比例、呼吸、记忆、共鸣、情绪和人与人之间的连接。',start:'开始探索音乐星海',continue:'进入 APP 主页'},
 en:{enter:'Enter in English',enEnter:'中文',home:'Home',tower:'Sound Tower',map:'Star Map',voice:'Voice',life:'Life',explore:'Explore',math:'Math',library:'Library',short:'Short',motion:'Less motion',back:'Home',search:'Search constellations…',open:'Open animation',source:'Open source',learn:'Learn more',complete:'Light this level',reset:'Reset progress',title:'Musicalife',sub:'A visual platform for exploring the beauty of music',poem:'Sail through waves, stars, body, language and world. Music is not only sound; it is ratio, breath, memory, resonance, emotion and connection.',start:'Start the music voyage',continue:'Enter app'}
};
let state={lang:localStorage.ml_lang||'',view:localStorage.ml_view||'home',compact:localStorage.ml_compact==='1',lowMotion:localStorage.ml_motion==='1',xp:+(localStorage.ml_xp||0),selected:null,filter:'all'};
const C={physics:'#7bdfff',ear:'#9ff4cf',theory:'#f8dd94',voice:'#ff93d7',brain:'#a98cff',life:'#ffc27f',world:'#7ae7d6',future:'#c1a7ff'};
const catLabel={zh:{physics:'声音物理',ear:'听觉心理',theory:'乐理数理',voice:'声乐人体',brain:'脑科学',life:'生活应用',world:'语言文化',future:'未来音乐'},en:{physics:'Sound physics',ear:'Psychoacoustics',theory:'Theory & math',voice:'Voice body',brain:'Brain science',life:'Life practice',world:'Culture',future:'Future music'}};
const termData=[
{id:'wave',cat:'physics',zh:'声波',en:'Sound wave',one:'声音是介质中的压力变化，像水面波一样传播。',oneEn:'Sound is pressure variation traveling through a medium.',anim:'wave',links:['Frequency','Amplitude','Medium']},
{id:'frequency',cat:'physics',zh:'频率',en:'Frequency',one:'一秒振动多少次；通常与音高相关。',oneEn:'Cycles per second; strongly related to pitch.',anim:'wave',links:['Pitch','Period','Octave']},
{id:'amplitude',cat:'physics',zh:'振幅',en:'Amplitude',one:'波动的大小；常与响度有关，但不是完全等同。',oneEn:'Wave size; related to loudness but not identical.',anim:'wave',links:['Loudness','dB']},
{id:'phase',cat:'physics',zh:'相位',en:'Phase',one:'波到达循环中哪个位置；相反相位可部分抵消。',oneEn:'Where a wave is in its cycle; opposite phase can cancel.',anim:'anc',links:['ANC','Interference']},
{id:'harmonic',cat:'physics',zh:'谐波 / 泛音',en:'Harmonics / overtones',one:'基频的整数倍频率共同决定音色。',oneEn:'Integer multiples of a fundamental shape timbre.',anim:'harmonics',links:['Timbre','Fourier','Resonance']},
{id:'fourier',cat:'physics',zh:'傅里叶思想',en:'Fourier idea',one:'复杂声音可以拆成很多简单正弦波。',oneEn:'Complex sound can be decomposed into simple sine waves.',anim:'fourier',links:['Spectrum','Timbre','Noise']},
{id:'resonance',cat:'physics',zh:'共振',en:'Resonance',one:'某些频率刚好适合一个物体或空间，于是被放大。',oneEn:'Some frequencies fit a body or cavity and are amplified.',anim:'resonance',links:['Formant','Instrument body','Room']},
{id:'standing',cat:'physics',zh:'驻波',en:'Standing wave',one:'波在空间中反射叠加，形成稳定的节点和腹部。',oneEn:'Reflected waves create stable nodes and antinodes.',anim:'resonance',links:['Tube','String','Scale']},
{id:'spectrum',cat:'physics',zh:'频谱',en:'Spectrum',one:'把声音按频率拆开后看到的能量分布。',oneEn:'Energy distribution across frequencies.',anim:'fourier',links:['Timbre','Noise','Masking']},
{id:'masking',cat:'ear',zh:'掩蔽效应',en:'Masking',one:'一个声音会盖住另一个声音，尤其在频率接近时。',oneEn:'One sound hides another, especially at nearby frequencies.',anim:'masking',links:['Critical band','White noise','Sleep']},
{id:'critical',cat:'ear',zh:'临界带',en:'Critical band',one:'耳朵把相近频率放在同一处理窗口，容易互相干扰。',oneEn:'Nearby frequencies share auditory processing windows.',anim:'masking',links:['Masking','Roughness']},
{id:'jnd',cat:'ear',zh:'JND 最小可觉差',en:'JND',one:'刚刚能觉察到变化的最小差异。',oneEn:'The smallest difference you can just notice.',anim:'jnd',links:['Pitch','Loudness','Training']},
{id:'loudness',cat:'ear',zh:'响度',en:'Loudness',one:'主观听到的大小，受声压、频率和时间影响。',oneEn:'Perceived intensity affected by pressure, frequency and time.',anim:'wave',links:['dB','Safety']},
{id:'roughness',cat:'ear',zh:'粗糙度',en:'Roughness',one:'相近频率快速互相拍动时产生的刺耳/紧张感。',oneEn:'Harshness from fast beating between nearby frequencies.',anim:'beating',links:['Dissonance','Critical band']},
{id:'binaural',cat:'ear',zh:'双耳效应',en:'Binaural hearing',one:'左右耳时间差和强度差帮助判断空间位置。',oneEn:'Interaural timing and level differences create space.',anim:'binaural',links:['Spatial sound','ANC']},
{id:'binauralBeat',cat:'ear',zh:'双耳节拍',en:'Binaural beat',one:'左右耳接近频率产生主观差频体验；证据需谨慎。',oneEn:'Close tones to each ear can create perceived beats; evidence is cautious.',anim:'binauralBeat',links:['Brain rhythms','Evidence']},
{id:'noise',cat:'ear',zh:'白/粉/棕噪声',en:'White / pink / brown noise',one:'不同频谱倾向的噪声，可用于掩蔽和声景稳定。',oneEn:'Noise spectra used for masking and stabilizing soundscapes.',anim:'noise',links:['Masking','Sleep','Focus']},
{id:'scale',cat:'theory',zh:'音阶',en:'Scale',one:'按规则排列的一组音高，像音乐的楼梯。',oneEn:'A structured set of pitches, like stairs for melody.',anim:'pitchStair',links:['Semitone','Mode','Relative pitch']},
{id:'interval',cat:'theory',zh:'音程',en:'Interval',one:'两个音之间的距离，是旋律和和声的骨架。',oneEn:'Distance between pitches; skeleton of melody and harmony.',anim:'pitchStair',links:['Ratio','Chord']},
{id:'temperament',cat:'theory',zh:'十二平均律',en:'Equal temperament',one:'把八度均分成 12 个相等比例的半音。',oneEn:'Divides the octave into 12 equal frequency ratios.',anim:'temperament',links:['Octave','Semitone','Keyboard']},
{id:'relativePitch',cat:'theory',zh:'相对音准',en:'Relative pitch',one:'听出两个音之间的关系；大多数学习最需要它。',oneEn:'Recognizing relationships between pitches; most practical for learning.',anim:'earTraining',links:['Interval','Scale']},
{id:'absolutePitch',cat:'theory',zh:'绝对音准',en:'Absolute pitch',one:'不用参照物直接命名音高；少见但不是音乐理解的唯一目标。',oneEn:'Naming pitches without reference; rare, not the only goal.',anim:'earTraining',links:['Pitch','Memory']},
{id:'metronome',cat:'theory',zh:'节拍器',en:'Metronome',one:'外部稳定脉冲，帮助身体建立时间网格。',oneEn:'External pulse that builds an internal timing grid.',anim:'metronome',links:['BPM','Entrainment','Practice']},
{id:'syncopation',cat:'theory',zh:'切分',en:'Syncopation',one:'把重音放到预期之外的位置，产生推动感。',oneEn:'Accent shifted away from expectation, creating drive.',anim:'syncopation',links:['Prediction','Groove']},
{id:'polyrhythm',cat:'theory',zh:'复节奏',en:'Polyrhythm',one:'两个时间网格同时存在，例如 3 对 4。',oneEn:'Multiple time grids at once, such as 3 over 4.',anim:'polyrhythm',links:['Math','Body']},
{id:'chord',cat:'theory',zh:'和弦',en:'Chord',one:'多个音同时发声，形成稳定、紧张或色彩。',oneEn:'Pitches sounding together, forming stability or tension.',anim:'chord',links:['Harmony','Choir']},
{id:'vocalFold',cat:'voice',zh:'声带振动',en:'Vocal fold vibration',one:'气流让声带周期性开合，产生人声的声源。',oneEn:'Airflow sets the vocal folds into vibration: the voice source.',anim:'vocalFold',links:['Airflow','Pitch','Onset']},
{id:'subglottal',cat:'voice',zh:'声门下压',en:'Subglottal pressure',one:'声带下方的气压，是音量和发声效率的重要动力。',oneEn:'Pressure below vocal folds; important for loudness and efficiency.',anim:'vocalFold',links:['Breath support','Closure']},
{id:'sovt',cat:'voice',zh:'SOVT 半闭合声道',en:'SOVT',one:'吸管、哼鸣、唇颤等让出口变窄，帮助声带省力协调。',oneEn:'Straw, hum and lip trill narrow the outlet to help efficient voicing.',anim:'sovt',links:['Back pressure','Warmup']},
{id:'chambers',cat:'voice',zh:'三腔 / 声道共鸣',en:'Vocal tract resonance',one:'口腔、咽腔、鼻腔改变频率放大方式；胸腔更多是感觉。',oneEn:'Mouth, pharynx and nasal tract shape resonances; chest is mostly sensation.',anim:'chambers',links:['Formant','Vowel']},
{id:'formant',cat:'voice',zh:'Formant 共振峰',en:'Formant',one:'声道放大的频率峰，决定元音和许多音色差异。',oneEn:'Resonance peaks of the vocal tract; crucial for vowels and timbre.',anim:'formant',links:['Vowel','Source-filter']},
{id:'tone',cat:'voice',zh:'声调 / 调值',en:'Tone contour',one:'语言中音高的相对高度和走向，普通话四声就是例子。',oneEn:'Pitch height and contour in language; Mandarin tones are examples.',anim:'toneContour',links:['Prosody','Melody']},
{id:'prosody',cat:'voice',zh:'语调 / 韵律',en:'Prosody',one:'说话的音高、重音、停顿和节奏，让语言变得像音乐。',oneEn:'Pitch, stress, pause and rhythm make speech musical.',anim:'prosody',links:['Emotion','Language']},
{id:'choir',cat:'voice',zh:'合唱与和声',en:'Choir & harmony',one:'多个声部同步呼吸、音准、音色与听觉反馈。',oneEn:'Voices align breath, pitch, timbre and listening.',anim:'choir',links:['Chord','Resonance','Social sync']},
{id:'prediction',cat:'brain',zh:'预测编码',en:'Predictive coding',one:'大脑不断猜下一步声音，再用误差更新理解。',oneEn:'The brain predicts the next sound and updates from error.',anim:'prediction',links:['Anticipation','Curiosity']},
{id:'dmn',cat:'brain',zh:'DMN 默认模式网络',en:'DMN',one:'与自传记忆、想象和内在叙事相关，熟悉音乐常会牵动它。',oneEn:'Linked to autobiographical memory, imagination and inner narrative.',anim:'memory',links:['Memory','Emotion']},
{id:'reward',cat:'brain',zh:'奖赏系统',en:'Reward system',one:'期待、解决、熟悉和惊喜会影响愉悦与动机。',oneEn:'Expectation, resolution, familiarity and surprise shape pleasure.',anim:'prediction',links:['Dopamine','Motivation']},
{id:'hrv',cat:'brain',zh:'HRV 心率变异性',en:'HRV',one:'心跳间隔的变化，可反映自主神经调节状态。',oneEn:'Variation in heartbeat intervals, related to autonomic regulation.',anim:'multisensory',links:['Breath','Vagus']},
{id:'entrainment',cat:'brain',zh:'节律夹带',en:'Entrainment',one:'身体和大脑会与外部节拍同步，帮助动作和注意。',oneEn:'Brain and body synchronize with external pulse.',anim:'metronome',links:['BPM','Movement']},
{id:'sleep',cat:'life',zh:'睡眠声景',en:'Sleep soundscape',one:'降低预测负荷，掩蔽突发声，让身体逐渐降档。',oneEn:'Lower prediction load, mask sudden noise, help downshift.',anim:'soundscape',links:['Noise','Relaxation']},
{id:'pain',cat:'life',zh:'疼痛管理',en:'Pain support',one:'音乐可辅助注意转移、呼吸同步和可控感，但不替代医疗。',oneEn:'Music may support attention shift, breathing and control; not medical replacement.',anim:'painGate',links:['Attention','Breath']},
{id:'mbct',cat:'life',zh:'音乐正念 / MBCT',en:'Music mindfulness',one:'不评价音乐，只观察声音、身体和注意力如何变化。',oneEn:'Observe sound, body and attention without judging.',anim:'mindfulness',links:['Attention','Emotion']},
{id:'soundscape',cat:'life',zh:'声景设计',en:'Soundscape design',one:'设计危险声、背景声、安全锚点和静音出口。',oneEn:'Design danger cues, background, safe anchors and exits.',anim:'soundscape',links:['Noise rights','Space']},
{id:'talkingDrum',cat:'world',zh:'会说话的鼓',en:'Talking drum',one:'某些鼓可模仿声调语言的音高轮廓和节奏。',oneEn:'Some drums imitate tonal language contours and rhythm.',anim:'talkingDrum',links:['Tone language','Rhythm']},
{id:'gamelan',cat:'world',zh:'甘美兰',en:'Gamelan',one:'层叠的金属打击乐、循环节奏和集体织体。',oneEn:'Layered metallophones, cyclic rhythm and collective texture.',anim:'polyrhythm',links:['Timbre','Culture']},
{id:'theremin',cat:'future',zh:'Theremin 特雷门琴',en:'Theremin',one:'不接触乐器，用手势改变电磁场控制音高和音量。',oneEn:'A no-touch instrument controlling pitch and volume by hand distance.',anim:'theremin',links:['Electronic','Sci-fi']},
{id:'sampler',cat:'future',zh:'采样器',en:'Sampler',one:'把声音切片、重排、变形，让世界成为乐器。',oneEn:'Slice and rearrange recorded sound; the world becomes an instrument.',anim:'sampler',links:['Media','Hip-hop']},
{id:'haptic',cat:'future',zh:'触觉音乐',en:'Haptic music',one:'把音乐转译成身体可感的振动，扩展“听”的方式。',oneEn:'Translate music into vibration, expanding what listening can mean.',anim:'haptic',links:['Accessibility','Future']}
];
const edges=[['wave','frequency'],['frequency','scale'],['frequency','harmonic'],['harmonic','fourier'],['harmonic','formant'],['fourier','spectrum'],['spectrum','masking'],['masking','critical'],['critical','roughness'],['phase','binauralBeat'],['phase','anc'],['binaural','soundscape'],['scale','interval'],['interval','chord'],['temperament','scale'],['relativePitch','interval'],['metronome','entrainment'],['metronome','syncopation'],['syncopation','prediction'],['polyrhythm','gamelan'],['chord','choir'],['vocalFold','subglottal'],['subglottal','sovt'],['sovt','chambers'],['chambers','formant'],['formant','tone'],['tone','prosody'],['prosody','talkingDrum'],['prediction','reward'],['prediction','dmn'],['hrv','mbct'],['sleep','noise'],['pain','mbct'],['soundscape','sleep'],['theremin','haptic'],['sampler','future']];
const anims=[
['portal','函数星海 / Function ocean','physics'],['wave','声波 / Wave','physics'],['harmonics','谐波 / Harmonics','physics'],['fourier','傅里叶 / Fourier','physics'],['resonance','共振管 / Resonance','physics'],['masking','掩蔽 / Masking','ear'],['noise','白粉棕噪声 / Noise spectra','ear'],['binaural','双耳定位 / Binaural space','ear'],['binauralBeat','双耳节拍 / Binaural beat','ear'],['anc','主动降噪 / ANC','ear'],['pitchStair','音阶楼梯 / Scale stairs','theory'],['temperament','十二平均律 / Equal temperament','theory'],['metronome','节拍器 / Metronome','theory'],['syncopation','切分 / Syncopation','theory'],['polyrhythm','复节奏 / Polyrhythm','theory'],['chord','和弦 / Chord','theory'],['vocalFold','声带 / Vocal folds','voice'],['sovt','SOVT 回压 / Straw voice','voice'],['chambers','三腔与声道 / Vocal tract','voice'],['formant','元音共振峰 / Formants','voice'],['toneContour','声调曲线 / Tone contours','voice'],['choir','合唱和声 / Choir harmony','voice'],['prediction','贝叶斯预测 / Predictive brain','brain'],['multisensory','多感官同步 / Multisensory sync','brain'],['painGate','疼痛支持 / Pain support','life'],['soundscape','声景房间 / Soundscape room','life'],['talkingDrum','会说话的鼓 / Talking drum','world'],['theremin','Theremin 手势 / Theremin','future'],['sampler','采样器 / Sampler','future'],['haptic','触觉音乐 / Haptic music','future']
];
const levels=[
{icon:'🌊',anim:'wave',zh:'声音从哪里来？',en:'Where does sound begin?',text:'声波、频率、振幅和相位是音乐宇宙的第一组法则。',textEn:'Waves, frequency, amplitude and phase are the first laws of the music universe.'},
{icon:'✨',anim:'harmonics',zh:'为什么同一个音有不同颜色？',en:'Why does one note have many colors?',text:'基频与谐波叠加，变成音色。',textEn:'Fundamental plus harmonics become timbre.'},
{icon:'🏛️',anim:'resonance',zh:'为什么空间会放大声音？',en:'Why can space amplify sound?',text:'共振让某些频率被房间、乐器和身体强调。',textEn:'Resonance lets rooms, instruments and bodies emphasize frequencies.'},
{icon:'👂',anim:'masking',zh:'耳朵如何选择声音？',en:'How does the ear choose sounds?',text:'掩蔽、临界带和双耳效应决定我们听见什么。',textEn:'Masking, critical bands and binaural hearing shape what we hear.'},
{icon:'🎼',anim:'pitchStair',zh:'音乐如何变成秩序？',en:'How does music become order?',text:'音阶、音程、调式和相对音准让声音可以被记忆。',textEn:'Scales, intervals, modes and relative pitch make sound memorable.'},
{icon:'⏱️',anim:'metronome',zh:'节奏如何带动身体？',en:'How does rhythm move the body?',text:'节拍器、切分、复节奏和夹带让身体进入时间。',textEn:'Metronome, syncopation, polyrhythm and entrainment bring the body into time.'},
{icon:'🗣️',anim:'vocalFold',zh:'人声是一件乐器',en:'The voice is an instrument',text:'气流、声带、声道和语言共同生成歌声。',textEn:'Airflow, vocal folds, vocal tract and language generate singing.'},
{icon:'🧠',anim:'prediction',zh:'为什么音乐会让人着迷？',en:'Why does music fascinate us?',text:'预测、惊喜、记忆和奖赏让音乐像故事。',textEn:'Prediction, surprise, memory and reward make music story-like.'},
{icon:'🫀',anim:'multisensory',zh:'音乐如何进入生活？',en:'How does music enter life?',text:'声音可以与呼吸、注意、动作和身体感觉同步。',textEn:'Sound can synchronize with breath, attention, motion and body feeling.'},
{icon:'🚀',anim:'theremin',zh:'未来音乐在哪里？',en:'Where is future music?',text:'电子、触觉、AI 和太空想象扩展了“听见”的边界。',textEn:'Electronic, haptic, AI and space imagination extend listening.'}
];
const voiceChapters=[
{t:'发声总模型',e:'Voice production model',anim:'vocalFold',steps:['肺部提供气流，不是喉咙硬挤。','气流经过声带，声带周期性开合形成声源。','声道像可变形滤波器，口腔、咽腔、鼻腔塑造音色。','语言和歌唱是同一套系统的不同组织方式。']},
{t:'气流与声门下压',e:'Airflow and subglottal pressure',anim:'vocalFold',steps:['做 8 秒 sss，观察气流是否抖动。','做 vvv 或 zzz，让气流带动轻微振动。','不要一次吸太多气；目标是稳定、弹性、可持续。']},
{t:'声带闭合：漏气、挤压、平衡',e:'Vocal fold closure',anim:'vocalFold',steps:['哈——：听漏气感。','呃——：感受挤压感，但不要用力练。','嗯——啊：从闭口到开口，保持轻松连续。']},
{t:'SOVT：吸管、哼鸣、唇颤',e:'SOVT: straw, hum, lip trill',anim:'sovt',steps:['先吹吸管 5 秒，不发声。','用吸管轻发 wu 5 秒。','做低到高再回来的滑音。','拿掉吸管，用 u-o-a 过渡。']},
{t:'三腔与共鸣澄清',e:'Vocal tract resonance',anim:'chambers',steps:['胸腔多是振动感觉，不是主要发声出口。','口腔和咽腔真实改变声道形状。','鼻腔参与鼻音；过度鼻化会影响清晰度。','训练目标不是“找一个腔”，而是调节声道滤波。']},
{t:'Formant 与元音地图',e:'Formants and vowel map',anim:'formant',steps:['mi-me-ma-mo-mu 慢慢转。','保持同一个音高，只改变嘴型。','观察声音从亮到暗、从窄到宽。']},
{t:'声调、语调与讲话音乐性',e:'Tone, prosody and speech music',anim:'toneContour',steps:['画出普通话四声线条。','同一句话说成疑问、安慰、坚定、讲故事。','记录音高、重音、停顿如何改变意义。']},
{t:'音准：相对音准优先',e:'Pitch: relative pitch first',anim:'earTraining',steps:['先听两个音谁高谁低。','再听距离：近、远、跳跃。','再练 sol-mi-do，不急着完整音阶。']},
{t:'节拍器训练',e:'Metronome practice',anim:'metronome',steps:['跟 60 BPM 拍手。','每四拍强调第一拍。','一拍分成两个，再分成三个。','关掉节拍器 4 小节，再回来检查稳定。']},
{t:'合唱：共鸣、和声与共调节',e:'Choir: resonance, harmony and co-regulation',anim:'choir',steps:['一个人唱 do，另一人唱 mi。','加入 sol，听稳定大三和弦。','观察音准、音色和呼吸如何互相影响。','合唱不是所有人一样大声，而是互相听见。']}
];
const lifeCards=[
{t:'睡前脑内噪声',e:'Racing mind before sleep',anim:'soundscape',now:'不用找“好听”，找“可以忽略”。',why:'低动态、无歌词、粉红噪声或雨声可降低预测负荷并掩蔽突发环境声。',steps:['先关掉歌词音乐。','音量小到刚好覆盖环境声。','10 分钟后降低音量。','记录：更困/更烦/更清醒。'],refs:['Music and sleep research','Psychoacoustics masking']},
{t:'ADHD 启动困难',e:'ADHD task initiation',anim:'metronome',now:'用节奏当外部执行功能。',why:'稳定 BPM 可以给身体一个开始动作的时间支架。',steps:['选 90–120 BPM 低歌词音乐。','只承诺做 3 分钟。','进入任务后换成低信息量 ambient。'],refs:['Rhythmic entrainment','Attention and background music']},
{t:'ASD / 感官过载',e:'Sensory overload',anim:'soundscape',now:'先减少刺激，不急着加音乐。',why:'过载时大脑可能需要更少预测误差和更高控制权。',steps:['停止刺耳音乐。','用可预测低动态声音。','设置静音出口。','不要用更大声压过去。'],refs:['Soundscape design','Noise and health']},
{t:'疼痛管理辅助',e:'Pain support',anim:'painGate',now:'把注意力放到节奏、呼吸和身体边界。',why:'音乐可能帮助注意转移、情绪调节和可控感，但不替代医疗。',steps:['选熟悉且安全的音乐。','跟随慢呼气。','给疼痛命名，不和它对抗。','严重疼痛及时就医。'],refs:['Music therapy and pain','Mindfulness-based pain support']},
{t:'记忆学习',e:'Memory learning',anim:'memory',now:'把信息变成节奏和旋律钩子。',why:'旋律、情绪和重复结构能作为回忆线索。',steps:['给流程配 4 拍节奏。','把关键词唱成短旋律。','复习时先哼旋律再回忆内容。'],refs:['Music and memory','Levitin']},
{t:'音乐正念 / MBCT',e:'Music mindfulness',anim:'mindfulness',now:'不评价音乐好不好，只观察变化。',why:'音乐可以作为注意锚点，让人观察声音、身体和念头。',steps:['听 60 秒。','标记听到的层次。','观察身体哪里改变。','声音消失后再观察 20 秒。'],refs:['MBCT','Music mindfulness']},
{t:'社交声音困难',e:'Social voice practice',anim:'prosody',now:'语气可以拆成音高、重音、停顿、速度。',why:'把“语气问题”变成可调参数，降低模糊社交压力。',steps:['同一句话说 4 个版本。','画音高线。','听哪一个更友好/更坚定。'],refs:['Prosody','Speech science']},
{t:'嗓音疲劳',e:'Voice fatigue',anim:'sovt',now:'不要硬撑。先减负，再温和恢复。',why:'沙哑、疼痛、失声可能提示声带负荷过高。',steps:['停止大声说话。','轻做吸管音或哼鸣。','补水和休息。','长期嘶哑找耳鼻喉/言语治疗师。'],refs:['NIDCD voice health','SOVT research']}
];
const instruments=[
{t:'Theremin',cat:'future',anim:'theremin',desc:'无接触电子乐器，手的位置控制音高和音量，像科幻中的声音光线。'},
{t:'Ondes Martenot',cat:'future',anim:'theremin',desc:'早期电子乐器，滑音与表情非常细腻。'},
{t:'Talking drum',cat:'world',anim:'talkingDrum',desc:'通过挤压鼓绳改变音高，模仿声调语言的轮廓。'},
{t:'Mbira',cat:'world',anim:'harmonics',desc:'拇指琴，金属簧片振动，循环纹理像小星群。'},
{t:'Gamelan',cat:'world',anim:'polyrhythm',desc:'印尼青铜打击乐群，层叠周期和闪亮音色。'},
{t:'Kora',cat:'world',anim:'harmonics',desc:'西非竖琴-鲁特琴，弦振动与叙事传统相连。'},
{t:'Hurdy-gurdy',cat:'world',anim:'resonance',desc:'轮擦弦乐器，像机械持续音与旋律的结合。'},
{t:'Handpan',cat:'world',anim:'resonance',desc:'金属自鸣体，泛音与共振非常迷人。'},
{t:'Modular synth',cat:'future',anim:'wave',desc:'用电压连接振荡器、滤波器和包络，像搭建声音电路。'},
{t:'Sampler',cat:'future',anim:'sampler',desc:'把世界的声音切片、变调、重组。'}
];
const timeline=['身体与口传','骨笛与鼓','记谱','宗教空间','剧场与歌剧','唱片','广播','磁带','合成器','采样器','DAW','流媒体','AI 生成','触觉与太空音乐'];
const sources=[
['Fastl & Zwicker','Psychoacoustics: Facts and Models','心理声学基础：掩蔽、响度、粗糙度、双耳听觉、音乐声学。','https://link.springer.com/book/10.1007/978-3-540-68888-4'],
['Daniel Levitin','This Is Your Brain on Music','音乐、大脑、记忆、奖赏与人类迷恋音乐的入口。','https://www.penguinrandomhouse.com/books/298639/this-is-your-brain-on-music-by-daniel-j-levitin/'],
['David Huron','Sweet Anticipation','音乐期待心理学：为什么下一步让人着迷。','https://direct.mit.edu/books/monograph/1961/Sweet-Anticipation'],
['Johan Sundberg','The Science of the Singing Voice','声乐科学：声源、声道、共鸣、歌唱声学。','https://www.cornellpress.cornell.edu/book/9780875805429/the-science-of-the-singing-voice/'],
['Open Music Theory','Open online textbook','开放乐理教材：音阶、节奏、和声、曲式、流行与爵士。','https://viva.pressbooks.pub/openmusictheory/'],
['musictheory.net','Lessons and exercises','乐理和练耳互动练习。','https://www.musictheory.net/lessons'],
['NIDCD','Voice and speech resources','发声、语音、嗓音健康的权威科普。','https://www.nidcd.nih.gov/health/voice-speech-and-language'],
['AMTA','Music therapy definition','严格音乐治疗定义和职业边界。','https://www.musictherapy.org/about/musictherapy/'],
['R. Murray Schafer','The Tuning of the World','声景、声音生态与世界如何被听见。','https://en.wikipedia.org/wiki/The_Tuning_of_the_World']
];
function L(k){return langPack[state.lang||'zh'][k]||k}function isEn(){return state.lang==='en'}function txt(a,b){return isEn()?b:a}
const app=$('#app');
function render(){document.body.classList.toggle('compact',state.compact);document.body.classList.toggle('lowMotion',state.lowMotion); if(!state.lang){renderGate(); return} renderShell()}
function renderGate(){app.innerHTML=`<section class="heroGate"><div class="gateCard"><canvas class="gateCanvas" id="gateCanvas"></canvas><h1 class="gateTitle">Musicalife</h1><p class="gateSub">一个探索音乐趣味的可视化平台<br/><span class="muted">A visual platform for exploring the beauty of music</span></p><p class="gatePoem">像乘坐一只知识的小船，穿过声波、星光、身体、语言和世界。音乐不是只有声音，它是比例、呼吸、记忆、共鸣、情绪和人与人之间的连接。</p><div class="actions"><button class="primary" onclick="setLang('zh')">中文进入</button><button class="secondary" onclick="setLang('en')">Enter in English</button></div></div></section>`; animateCanvas($('#gateCanvas'),'portal')}
function renderShell(){let nav=[['home','✦',L('home')],['tower','⛵',L('tower')],['map','✧',L('map')],['voice','♬',L('voice')],['life','♥',L('life')],['explore','☄',L('explore')],['math','∞',L('math')],['library','⌁',L('library')]]; app.innerHTML=`<div class="shell"><aside class="side"><div class="brand"><div class="brandOrb">♪</div><div><h1>Musicalife</h1><small>${txt('音乐星海','music constellation')}</small></div></div><div class="nav">${nav.map(n=>`<button class="${state.view===n[0]?'active':''}" onclick="setView('${n[0]}')"><span>${n[1]}</span>${n[2]}</button>`).join('')}</div><div class="sideTools"><button class="ghost" onclick="toggleLang()">${state.lang==='zh'?'English':'中文'}</button><button class="ghost" onclick="toggleCompact()">${L('short')} ${state.compact?'✓':''}</button><button class="ghost" onclick="toggleMotion()">${L('motion')} ${state.lowMotion?'✓':''}</button></div></aside><main class="main"><div class="topbar"><div class="crumbs"><button class="crumb" onclick="setView('home')">🏠 ${L('back')}</button><span class="crumb">${nav.find(n=>n[0]===state.view)?.[2]||''}</span></div><div class="actions" style="margin:0"><button class="ghost" onclick="toggleLang()">${state.lang==='zh'?'EN':'中文'}</button><button class="ghost" onclick="toggleCompact()">${L('short')}</button></div></div><div id="page"></div></main></div><nav class="bottomNav">${nav.slice(0,6).map(n=>`<button class="${state.view===n[0]?'active':''}" onclick="setView('${n[0]}')"><span>${n[1]}</span><span>${n[2]}</span></button>`).join('')}</nav>`; renderPage()}
function setLang(l){state.lang=l;localStorage.ml_lang=l;render()}function toggleLang(){setLang(state.lang==='zh'?'en':'zh')}function setView(v){state.view=v;localStorage.ml_view=v;renderShell()}function toggleCompact(){state.compact=!state.compact;localStorage.ml_compact=state.compact?'1':'0';renderShell()}function toggleMotion(){state.lowMotion=!state.lowMotion;localStorage.ml_motion=state.lowMotion?'1':'0';renderShell()}
function header(title,subtitle){return `<section class="panel"><div class="pageTitle"><div><h2>${title}</h2><p>${subtitle}</p></div></div></section>`}
function renderPage(){let p=$('#page'); if(state.view==='home')p.innerHTML=home(); if(state.view==='tower')p.innerHTML=tower(); if(state.view==='map'){p.innerHTML=mapPage(); setTimeout(drawGraph,20)} if(state.view==='voice')p.innerHTML=voice(); if(state.view==='life')p.innerHTML=life(); if(state.view==='explore')p.innerHTML=explore(); if(state.view==='math')p.innerHTML=math(); if(state.view==='library')p.innerHTML=library(); $$('.miniCanvas').forEach(c=>animateCanvas(c,c.dataset.anim));}
function home(){return `${header(txt('Musicalife｜音乐如何改善生活','Musicalife｜A visual voyage into music'),txt('不是普通课程，而是一片音乐星海：你可以从声音、身体、乐理、语言、生活和世界文化进入，逐渐看见音乐如何连接一切。','Not a course page, but a music cosmos: enter through sound, body, theory, language, life and world culture.'))}<section class="panel"><canvas class="bigCanvas homeConstellation miniCanvas" data-anim="portal"></canvas><div class="grid"><div class="card cat-physics" onclick="setView('tower')"><h3>⛵ ${txt('开始声之塔','Start Sound Tower')}</h3><p>${txt('像游戏一样逐层解锁声音法则。','Unlock musical laws level by level.')}</p><div class="bar"></div></div><div class="card cat-brain" onclick="setView('map')"><h3>✧ ${txt('打开知识星盘','Open star map')}</h3><p>${txt('专业名词像星座一样连接起来。','Terms connect like constellations.')}</p><div class="bar"></div></div><div class="card cat-voice" onclick="setView('voice')"><h3>♬ ${txt('进入声乐实验室','Enter Voice Lab')}</h3><p>${txt('用气流、声带、共鸣、音阶理解人声。','Understand voice through airflow, folds, resonance and scale.')}</p><div class="bar"></div></div><div class="card cat-life" onclick="setView('life')"><h3>♥ ${txt('把音乐带回生活','Bring music into life')}</h3><p>${txt('睡眠、专注、疼痛、记忆、情绪、正念。','Sleep, focus, pain, memory, emotion and mindfulness.')}</p><div class="bar"></div></div><div class="card cat-world" onclick="setView('explore')"><h3>☄ ${txt('探索世界音乐','Explore world music')}</h3><p>${txt('语言、乐器、媒介史、科幻与未来音乐。','Language, instruments, media history, sci-fi and future music.')}</p><div class="bar"></div></div><div class="card cat-theory" onclick="setView('math')"><h3>∞ ${txt('音乐里的数学','Math of music')}</h3><p>${txt('频率比、谐波、节拍函数、傅里叶与和声。','Ratios, harmonics, rhythmic functions, Fourier and harmony.')}</p><div class="bar"></div></div></div></section>`}
function tower(){return `${header(txt('声之塔｜像游戏一样理解音乐','Sound Tower｜Learn music like an adventure'),txt('每一关是一个音乐法则。点开动画，完成小任务，Musicalife 会在本地保存你的星光 XP。','Each level is a law of music. Open the animation, finish a tiny task, and your XP is saved locally.'))}<section class="panel"><div class="xpBar"><span style="width:${Math.min(100,state.xp)}%"></span></div><p class="muted">XP ${state.xp}/100</p>${levels.map((lv,i)=>`<div class="level"><div class="orb">${lv.icon}</div><div><h3>${txt(lv.zh,lv.en)}</h3><p class="muted">${txt(lv.text,lv.textEn)}</p></div><button class="primary" onclick="openAnimation('${lv.anim}');addXP(7)">${L('open')}</button></div>`).join('')}<button class="ghost" onclick="localStorage.ml_xp=0;state.xp=0;renderShell()">${L('reset')}</button></section>`}
function mapPage(){let filters=['all','physics','ear','theory','voice','brain','life','world','future']; return `${header(txt('知识星盘｜专业名词关系图','Knowledge Star Map｜Concept constellation'),txt('没有中心遮挡。每个星辰都是一个专业名词；点击后可以看到解释、动画、相关概念和来源。','No central blocker. Every star is a term; click it to see explanation, animation, related concepts and sources.'))}<section class="panel graphWrap"><div class="graphBar"><input id="termSearch" placeholder="${L('search')}" oninput="drawGraph()"/><div class="filterRow">${filters.map(f=>`<button class="${state.filter===f?'active':''}" onclick="state.filter='${f}';drawGraph()">${f==='all'?txt('全部','All'):catLabel[state.lang][f]}</button>`).join('')}</div></div><svg class="graphSvg" id="graph"></svg></section><section class="detailDrawer" id="termDetail"><p class="muted">${txt('点击一颗星辰，查看它如何连接声波、身体、生活与世界。','Click a star to see how it connects waves, body, life and world.')}</p></section>`}
function voice(){return `${header(txt('Voice Lab｜声乐、说话与发声原理','Voice Lab｜Singing, speech and voice science'),txt('声乐不是玄学：它从气流开始，经过声带振动和声道滤波，最后成为语言、旋律、音色和情绪。','Voice is not magic: airflow, vocal fold vibration and vocal tract filtering become speech, melody, timbre and emotion.'))}<section class="panel"><div class="grid"><div class="card cat-voice wide"><h3>${txt('人声总公式','Voice formula')}</h3><p class="muted">${txt('肺部气流 → 声门下压 → 声带振动 → 声道滤波 → 元音/吐字 → 歌声与语言。','Airflow → subglottal pressure → fold vibration → vocal tract filter → vowel/articulation → singing and speech.')}</p><canvas class="miniCanvas" data-anim="vocalFold"></canvas></div><div class="card cat-theory"><h3>${txt('声乐串联乐理','Voice connects theory')}</h3><p>${txt('音高来自振动频率；音准来自相对关系；节奏来自身体时间；和声来自多个声部的比例。','Pitch comes from vibration; intonation from relationships; rhythm from body time; harmony from ratios of voices.')}</p><div class="bar"></div></div></div>${voiceChapters.map(ch=>`<details class="accordion"><summary>${ch.t} <span class="muted">${ch.e}</span></summary><div class="inner"><canvas class="miniCanvas" data-anim="${ch.anim}"></canvas>${ch.steps.map((s,i)=>`<div class="step"><span class="num">${i+1}</span><span>${s}</span></div>`).join('')}<button class="secondary" onclick="openAnimation('${ch.anim}')">${L('open')}</button></div></details>`).join('')}</section>`}
function life(){return `${header(txt('生活声音工具箱','Sound tools for daily life'),txt('每张卡先给“立刻怎么做”，再展开机制、步骤和资料。音乐可作为生活支持，不替代医疗或专业治疗。','Each card starts with what to do now, then expands mechanism, steps and sources. Music supports life; it does not replace medical care.'))}<section class="panel"><div class="grid">${lifeCards.map(c=>`<div class="card cat-life half"><h3>${c.t}</h3><p><b>${txt('立刻做：','Now:')}</b>${c.now}</p><canvas class="miniCanvas" data-anim="${c.anim}"></canvas><details class="accordion"><summary>${L('learn')}</summary><div class="inner"><p><b>${txt('机制','Mechanism')}：</b>${c.why}</p>${c.steps.map((s,i)=>`<div class="step"><span class="num">${i+1}</span><span>${s}</span></div>`).join('')}<p class="muted">${txt('资料关键词','Source keywords')}: ${c.refs.join(' · ')}</p></div></details></div>`).join('')}</div></section>`}
function explore(){return `${header(txt('探索馆｜世界、乐器、媒介与未来音乐','Exploration Museum｜World, instruments, media and future music'),txt('音乐不只在钢琴和歌单里。它也在语言、仪式、科技、身体、星空和未来想象里。','Music is not only in piano and playlists. It lives in language, ritual, technology, body, stars and future imagination.'))}<section class="panel"><h3>${txt('奇妙乐器馆','Instrument Zoo')}</h3><div class="grid">${instruments.map(i=>`<div class="card cat-${i.cat}"><h3>${i.t}</h3><p>${i.desc}</p><canvas class="miniCanvas" data-anim="${i.anim}"></canvas><button class="secondary" onclick="openAnimation('${i.anim}')">${L('open')}</button><div class="bar"></div></div>`).join('')}</div></section><section class="panel"><h3>${txt('音乐媒介发展史','Music media timeline')}</h3><div class="timeline">${timeline.map((t,i)=>`<div class="timeCard"><span class="tag">${i+1}</span><h3>${t}</h3><p class="muted">${txt('展开后可继续加入代表声音、人物、技术和社会变化。','Expandable with representative sounds, people, technology and social change.')}</p></div>`).join('')}</div></section><section class="panel"><div class="grid"><div class="card cat-world half"><h3>${txt('语言与音乐','Language and music')}</h3><p>${txt('声调语言、说唱、诗歌、戏曲和会说话的鼓，都说明语言本身具有旋律和节奏。','Tone languages, rap, poetry, opera and talking drums show that language itself has melody and rhythm.')}</p><canvas class="miniCanvas" data-anim="toneContour"></canvas></div><div class="card cat-future half"><h3>${txt('科幻音乐','Sci-fi music')}</h3><p>${txt('真空不能传播普通声波，但音乐可以转译成无线电、触觉振动、光、脑机信号。','Vacuum cannot carry ordinary sound, but music can become radio, haptic vibration, light or brain-computer signals.')}</p><canvas class="miniCanvas" data-anim="haptic"></canvas></div></div></section>`}
function math(){return `${header(txt('Math of Music｜音乐里的数理之美','Math of Music｜The beauty of musical mathematics'),txt('像公式一样优美：频率比变成音程，周期变成节奏，谐波变成音色，傅里叶让世界的声音被拆解又重组。','Beautiful like formulas: frequency ratios become intervals, periods become rhythm, harmonics become timbre, Fourier decomposes and recomposes sound.'))}<section class="panel"><div class="grid"><div class="card cat-theory half"><h3>f = 1 / T</h3><p>${txt('频率是周期的倒数。周期越短，频率越高，常听成更高的音。','Frequency is the reciprocal of period. Shorter period means higher frequency, often perceived as higher pitch.')}</p><canvas class="miniCanvas" data-anim="wave"></canvas></div><div class="card cat-theory half"><h3>Octave = 2 : 1</h3><p>${txt('八度的频率约翻倍：A4 440 Hz，A5 880 Hz。','An octave doubles frequency: A4 440 Hz, A5 880 Hz.')}</p><canvas class="miniCanvas" data-anim="pitchStair"></canvas></div><div class="card cat-theory half"><h3>Harmonics = f, 2f, 3f…</h3><p>${txt('整数倍频率叠加，形成音色和共鸣的基础。','Integer multiples create the basis of timbre and resonance.')}</p><canvas class="miniCanvas" data-anim="harmonics"></canvas></div><div class="card cat-theory half"><h3>12-TET = 2^(n/12)</h3><p>${txt('十二平均律让每个半音的比例相同，方便转调。','Equal temperament gives equal semitone ratios, making modulation practical.')}</p><canvas class="miniCanvas" data-anim="temperament"></canvas></div><div class="card cat-theory half"><h3>${txt('节奏是时间函数','Rhythm as time function')}</h3><p>${txt('节拍器像周期性脉冲；切分就是重音偏离预期网格。','A metronome is a periodic pulse; syncopation shifts accents away from the expected grid.')}</p><canvas class="miniCanvas" data-anim="syncopation"></canvas></div><div class="card cat-theory half"><h3>${txt('傅里叶：声音的棱镜','Fourier: prism of sound')}</h3><p>${txt('像光通过棱镜，复杂声音可以拆成频率成分。','Like light through a prism, complex sound can split into frequency components.')}</p><canvas class="miniCanvas" data-anim="fourier"></canvas></div></div></section>`}
function library(){return `${header(txt('资料图书馆','Source Library'),txt('这里放可查证的书籍、课程和专业组织。按钮已避开装饰线，方便手机点击。','A verifiable library of books, courses and organizations. Source buttons avoid decorative lines and are easy to tap.'))}<section class="panel"><div class="grid">${sources.map(s=>`<div class="card cat-brain"><h3>${s[0]}</h3><p><b>${s[1]}</b></p><p>${s[2]}</p><div class="sourceLinks"><a href="${s[3]}" target="_blank" rel="noopener">${L('source')}</a></div></div>`).join('')}</div></section>`}
function addXP(n){state.xp=Math.min(100,state.xp+n);localStorage.ml_xp=state.xp}
function selectTerm(id){let term=termData.find(t=>t.id===id); state.selected=id; drawGraph(); let d=$('#termDetail'); if(!d)return; let related=edges.filter(e=>e.includes(id)).flat().filter(x=>x!==id); d.innerHTML=`<h3>${txt(term.zh,term.en)} <span class="tag">${catLabel[state.lang][term.cat]}</span></h3><p>${txt(term.one,term.oneEn)}</p><div class="sourceLinks"><button class="secondary" onclick="openAnimation('${term.anim}')">${L('open')}</button>${related.map(r=>{let tt=termData.find(t=>t.id===r);return `<button class="ghost" onclick="selectTerm('${r}')">${txt(tt.zh,tt.en)}</button>`}).join('')}</div><p class="muted deep">${txt('关系','Links')}: ${term.links.join(' · ')}</p>`; d.scrollIntoView({behavior:'smooth',block:'nearest'})}
function drawGraph(){let svg=$('#graph'); if(!svg)return; let search=($('#termSearch')?.value||'').toLowerCase(); let terms=termData.filter(t=>(state.filter==='all'||t.cat===state.filter)&&(!search||(t.zh+t.en+t.one+t.oneEn).toLowerCase().includes(search))); let w=svg.clientWidth||1000,h=svg.clientHeight||560; let centers={physics:[w*.22,h*.20],ear:[w*.52,h*.18],theory:[w*.80,h*.23],voice:[w*.22,h*.56],brain:[w*.52,h*.55],life:[w*.80,h*.55],world:[w*.35,h*.82],future:[w*.68,h*.82]}; let by={}; terms.forEach(t=>(by[t.cat]=by[t.cat]||[]).push(t)); let pos={}; Object.entries(by).forEach(([cat,arr])=>{let [cx,cy]=centers[cat]||[w/2,h/2],R=42+arr.length*6; arr.forEach((t,i)=>{let a=-Math.PI/2+i*2*Math.PI/arr.length; pos[t.id]=[cx+Math.cos(a)*R,cy+Math.sin(a)*R]})}); let html=`<defs><filter id="glow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>`; edges.forEach(e=>{if(pos[e[0]]&&pos[e[1]]){let hi=state.selected&&e.includes(state.selected);html+=`<line class="edge ${hi?'highlight':''}" x1="${pos[e[0]][0]}" y1="${pos[e[0]][1]}" x2="${pos[e[1]][0]}" y2="${pos[e[1]][1]}"/>`}}); terms.forEach(t=>{let [x,y]=pos[t.id]; let r=state.selected===t.id?12:8; html+=`<g class="node" onclick="selectTerm('${t.id}')"><circle cx="${x}" cy="${y}" r="${r}" fill="${C[t.cat]}" filter="url(#glow)"></circle><text x="${x+12}" y="${y+4}">${txt(t.zh,t.en)}</text></g>`}); svg.innerHTML=html}
function openAnimation(type){let item=anims.find(a=>a[0]===type)||[type,type,'physics']; let title=item[1]; let controls=['wave','harmonics','metronome','pitchStair','vocalFold','formant','prediction','portal'].includes(type); document.body.insertAdjacentHTML('beforeend',`<div class="modal" onclick="if(event.target.classList.contains('modal'))closeModal()"><div class="modalCard"><div class="modalHead"><div><h2>${title}</h2><p class="muted">${animExplain(type)}</p></div><button class="close" onclick="closeModal()">✕</button></div><canvas class="bigCanvas" id="animCanvas"></canvas>${controls?`<div class="controls"><label class="control"><span>${txt('频率 / 速度','frequency / speed')}</span><input id="ctrlA" type="range" min="1" max="10" value="4"/><b id="ctrlAv">4</b></label><label class="control"><span>${txt('幅度 / 强度','amplitude / strength')}</span><input id="ctrlB" type="range" min="1" max="10" value="6"/><b id="ctrlBv">6</b></label></div>`:''}<div class="actions"><button class="secondary" onclick="openAnimation('${type}')">${txt('重播','Replay')}</button><button class="secondary" onclick="closeModal()">${txt('关闭','Close')}</button></div></div></div>`); let c=$('#animCanvas'); animateCanvas(c,type); ['ctrlA','ctrlB'].forEach(id=>{let el=$('#'+id); if(el)el.oninput=()=>{$('#'+id+'v').textContent=el.value}})}
function closeModal(){document.querySelector('.modal')?.remove()}
function animExplain(type){const m={portal:['高维函数降维成可听见的波，像音乐星海的入口。','A high-dimensional function becomes visible waves: the entrance to the music cosmos.'],wave:['拖动参数可以理解频率、周期、振幅与音高/响度的关系。','Change parameters to see frequency, period, amplitude and pitch/loudness.'],harmonics:['基频加上整数倍频率，形成音色。','Fundamental plus integer multiples creates timbre.'],fourier:['复杂声音像光谱一样被拆成频率成分。','Complex sound splits into frequency components like a spectrum.'],resonance:['当频率适合空间，声音被放大。','When frequency fits a space, sound is amplified.'],vocalFold:['气流让声带周期性开合，形成声源。','Airflow makes folds vibrate, creating a voice source.'],chambers:['三腔不是神秘位置，而是声道滤波与身体感觉的组合。','Vocal chambers are tract filtering plus body sensation.'],metronome:['节拍器给身体一个外部时间网格。','A metronome gives the body an external time grid.'],choir:['多个声音以比例和听觉反馈组织成和声。','Voices organize into harmony through ratios and feedback.']}; return txt(...(m[type]||['点击观察声音如何变成知识。','Watch sound become knowledge.']))}
function animateCanvas(canvas,type){if(!canvas)return; const ctx=canvas.getContext('2d'); let raf; function resize(){let rect=canvas.getBoundingClientRect();canvas.width=Math.max(300,rect.width)*devicePixelRatio;canvas.height=Math.max(150,rect.height)*devicePixelRatio} resize(); const ro=new ResizeObserver(resize); ro.observe(canvas); function frame(ts){drawAnim(ctx,canvas,type,ts/1000); if(!state.lowMotion) raf=requestAnimationFrame(frame)} frame(0); canvas._stop=()=>{ro.disconnect();cancelAnimationFrame(raf)}}
function drawAnim(ctx,canvas,type,t){let W=canvas.width,H=canvas.height,dpr=devicePixelRatio||1; let w=W/dpr,h=H/dpr; ctx.setTransform(dpr,0,0,dpr,0,0); ctx.clearRect(0,0,w,h); let cx=w/2,cy=h/2; let g=ctx.createLinearGradient(0,0,w,h); g.addColorStop(0,'rgba(123,223,255,.10)'); g.addColorStop(.45,'rgba(169,140,255,.08)'); g.addColorStop(1,'rgba(255,147,215,.08)'); ctx.fillStyle=g; ctx.fillRect(0,0,w,h); function line(col,width=2){ctx.strokeStyle=col;ctx.lineWidth=width;ctx.lineCap='round'} function text(s,x,y,size=14,col='#f8edff'){ctx.fillStyle=col;ctx.font=`${size}px ${getComputedStyle(document.body).fontFamily}`;ctx.fillText(s,x,y)}
 let A=+($('#ctrlB')?.value||6)/10, F=+($('#ctrlA')?.value||4); ctx.save();
 if(type==='portal'){for(let j=0;j<6;j++){line(['#7bdfff','#a98cff','#ff93d7','#f8dd94','#9ff4cf','#c1a7ff'][j],1.6);ctx.beginPath();for(let x=0;x<w;x++){let u=x/w*2*Math.PI;let y=cy+Math.sin(u*(1+j*.45)+t*(.5+j*.1))*h*(.10/(1+j*.08))+Math.cos(u*3.1+t*.7+j)*h*.04+j*6-18;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()} for(let i=0;i<70;i++){ctx.globalAlpha=.25+.45*Math.sin(t+i);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc((i*53+t*18)%w,(Math.sin(i*7+t*.3)*.5+.5)*h,1.2,0,7);ctx.fill()} ctx.globalAlpha=1;text('music = wave + ratio + breath + memory',24,36,15,'#f8dd94')}
 else if(type==='wave'){line('#7bdfff',3);ctx.beginPath();for(let x=0;x<w;x++){let y=cy+Math.sin(x/w*F*2*Math.PI+t*2)*h*.28*A;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();text('frequency ↔ pitch',20,34);text('amplitude ↔ loudness',20,58,14,'#f8dd94')}
 else if(type==='harmonics'||type==='fourier'){let n=type==='fourier'?12:7;line('#ff93d7',2);ctx.beginPath();for(let x=0;x<w;x++){let y=cy;let u=x/w*2*Math.PI;for(let k=1;k<=n;k++)y+=Math.sin(u*k+t*(.4+k*.05))*h*.16/k;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();for(let k=1;k<=n;k++){let bh=h*.42/k;ctx.fillStyle=`rgba(123,223,255,${.16+.04*k})`;ctx.fillRect(35+k*(w-80)/n,h-30-bh,10,bh)}text(type==='fourier'?'complex sound → frequency components':'f + 2f + 3f ... → timbre',18,34,15,'#f8dd94')}
 else if(type==='resonance'||type==='chambers'){ctx.fillStyle='rgba(255,255,255,.10)';ctx.beginPath();ctx.roundRect(40,cy-44,w-80,88,42);ctx.fill();line('#f8dd94',2.4);for(let k=1;k<=5;k++){ctx.beginPath();for(let x=55;x<w-55;x++){let y=cy+Math.sin((x-55)/(w-110)*Math.PI*k)*24*Math.sin(t*1.4+k);if(x===55)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}text(type==='chambers'?'pharynx · mouth · nasal tract shape resonance':'resonant space amplifies selected frequencies',18,34)}
 else if(type==='masking'||type==='noise'){for(let i=0;i<260;i++){ctx.fillStyle=`rgba(190,220,255,${Math.random()*.08})`;ctx.fillRect(Math.random()*w,Math.random()*h,2,2)}line('#f8dd94',3);ctx.beginPath();for(let x=0;x<w;x++){let y=cy+Math.sin(x*.08+t*4)*16;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();ctx.fillStyle='rgba(123,223,255,.18)';ctx.fillRect(w*.16,cy-68,w*.68,136);text(type==='noise'?'white / pink / brown noise = different spectra':'masking: stable sound covers unpredictable sound',18,34)}
 else if(type==='binaural'||type==='binauralBeat'){ctx.fillStyle='rgba(255,255,255,.13)';ctx.beginPath();ctx.arc(w*.25,cy,34,0,7);ctx.arc(w*.75,cy,34,0,7);ctx.fill();line('#7bdfff',2);for(let side of [.25,.75]){ctx.beginPath();for(let x=0;x<w;x++){let y=cy+(side-.5)*86+Math.sin(x*.055+t*(type==='binauralBeat'?4.4:3)+side*6)*18;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}text(type==='binauralBeat'?'close left/right tones → perceived beat':'left/right timing + level → spatial hearing',18,34)}
 else if(type==='anc'){line('rgba(123,223,255,.86)',2);ctx.beginPath();for(let x=0;x<w;x++){let y=cy+Math.sin(x*.035+t*3)*42;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();line('rgba(255,147,215,.86)',2);ctx.beginPath();for(let x=0;x<w;x++){let y=cy-Math.sin(x*.035+t*3)*39;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();line('#f8dd94',3);ctx.beginPath();for(let x=0;x<w;x++){let y=cy+Math.sin(x*.035+t*3)*4;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();text('noise + anti-noise ≈ less rumble',18,34)}
 else if(type==='pitchStair'||type==='temperament'||type==='earTraining'){let steps=12;for(let i=0;i<steps;i++){let x=30+i*(w-60)/steps,y=h-42-i*(h-92)/steps;ctx.fillStyle=i%2?'rgba(169,140,255,.25)':'rgba(248,221,148,.22)';ctx.fillRect(x,y,(w-65)/steps,24);text(i===0?'do':i===4?'mi':i===7?'sol':i===11?'ti':'',x+3,y+17,12)}line('#7bdfff',2);ctx.beginPath();for(let i=0;i<steps;i++){let x=30+i*(w-60)/steps,y=h-30-i*(h-92)/steps;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();text(type==='temperament'?'12 equal ratio steps inside one octave':'scale stairs train relative pitch',18,34)}
 else if(type==='metronome'||type==='syncopation'||type==='polyrhythm'){let bpm=40+F*18,beat=(t*bpm/60)%4;for(let i=0;i<4;i++){ctx.fillStyle=i<beat?'#f8dd94':'rgba(255,255,255,.13)';ctx.beginPath();ctx.arc(60+i*(w-120)/3,cy,22+(i===Math.floor(beat)?8:0),0,7);ctx.fill()}if(type==='polyrhythm'){for(let i=0;i<3;i++){ctx.fillStyle='rgba(123,223,255,.72)';ctx.beginPath();ctx.arc(80+i*(w-160)/2,cy+58,15,0,7);ctx.fill()}}if(type==='syncopation'){ctx.fillStyle='rgba(255,147,215,.78)';ctx.beginPath();ctx.arc(60+((beat+.5)%4)*(w-120)/3,cy-55,14,0,7);ctx.fill()}text(type==='polyrhythm'?'3 over 4: two time grids':type==='syncopation'?'syncopation: accent moves off-grid':'metronome = external time grid',18,34)}
 else if(type==='chord'||type==='choir'){let ys=[cy+60,cy+18,cy-28,cy-70],cols=['#7bdfff','#f8dd94','#ff93d7','#9ff4cf'];ys.forEach((y,i)=>{line(cols[i],2);ctx.beginPath();for(let x=20;x<w-20;x++){let yy=y+Math.sin(x*.02*(i+1)+t*2)*10;if(x===20)ctx.moveTo(x,yy);else ctx.lineTo(x,yy)}ctx.stroke();text(['do','mi','sol','ti'][i],w-48,y+5,14,cols[i])});text('many voices → ratio → harmony → shared breath',18,34)}
 else if(type==='vocalFold'){let air=(Math.sin(t*3)+1)/2;ctx.fillStyle='rgba(123,223,255,.16)';for(let i=0;i<9;i++){ctx.beginPath();ctx.arc(w*.18+i*w*.075,h-38-air*94,5,0,7);ctx.fill()}ctx.fillStyle='#ff93d7';ctx.beginPath();ctx.ellipse(cx-18,cy,18,72,Math.sin(t*10)*.08,0,7);ctx.ellipse(cx+18,cy,18,72,-Math.sin(t*10)*.08,0,7);ctx.fill();line('#f8dd94',2);ctx.beginPath();ctx.moveTo(cx,cy-72);ctx.lineTo(cx,cy+72);ctx.stroke();text('airflow + vocal fold closure = voice source',18,34)}
 else if(type==='sovt'){ctx.fillStyle='rgba(255,147,215,.32)';ctx.fillRect(w*.22,cy-26,w*.34,52);ctx.fillStyle='rgba(123,223,255,.26)';ctx.fillRect(w*.55,cy-8,w*.30,16);line('#f8dd94',2);for(let i=0;i<7;i++){ctx.beginPath();ctx.arc(w*.38,cy,18+i*12+(t*18%12),0,7);ctx.stroke()}text('semi-closed outlet → back pressure → easier vibration',18,34)}
 else if(type==='formant'){let vowels=['i','e','a','o','u'];vowels.forEach((v,i)=>{let x=55+i*(w-110)/4;ctx.fillStyle='rgba(255,255,255,.11)';ctx.beginPath();ctx.ellipse(x,cy,22+i*4,50-i*5,0,0,7);ctx.fill();text(v,x-4,cy+76,18,'#f8dd94')});line('#7bdfff',2);ctx.beginPath();for(let x=0;x<w;x++){let y=h-45-(Math.sin(x*.03+t)+1)*20-(Math.sin(x*.08+t*1.2)+1)*25;if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();text('vowel = vocal tract filter shape',18,34)}
 else if(type==='toneContour'||type==='prosody'){[0,1,2,3].forEach((i)=>{let x0=40+i*(w-80)/4,ww=(w-110)/4;line(['#f8dd94','#7bdfff','#ff93d7','#9ff4cf'][i],3);ctx.beginPath();for(let x=0;x<ww;x++){let u=x/ww;let val=i===0?.22:i===1?1-u:i===2?(u<.55?.75+u*.25:.9-(u-.55)*1.5):u;let y=h-50-val*(h-92);if(x===0)ctx.moveTo(x0+x,y);else ctx.lineTo(x0+x,y)}ctx.stroke();text(['1','2','3','4'][i],x0+ww/2,h-22,16)});text('tone contour: language becomes melody',18,34)}
 else if(type==='prediction'){for(let i=0;i<5;i++){ctx.fillStyle=`rgba(169,140,255,${.12+i*.08})`;ctx.beginPath();ctx.arc(w*.18+i*w*.16,cy+Math.sin(t+i)*38,24+i*3,0,7);ctx.fill()}line('#f8dd94',2);ctx.beginPath();for(let x=30;x<w-30;x++){let y=cy+Math.sin(x*.025+t)*40+Math.sin(x*.07+t*2)*10;if(x===30)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();text('expectation → surprise → update → pleasure',18,34)}
 else if(type==='multisensory'||type==='mindfulness'||type==='painGate'||type==='memory'){['sound','breath','body','attention'].forEach((s,i)=>{let r=22+Math.sin(t*1.6+i)*8;ctx.fillStyle=['rgba(123,223,255,.55)','rgba(159,244,207,.45)','rgba(255,147,215,.45)','rgba(248,221,148,.45)'][i];ctx.beginPath();ctx.arc(w*(.2+i*.2),cy,r,0,7);ctx.fill();text(s,w*(.2+i*.2)-24,cy+58,12)});line('#fff',1.5);ctx.beginPath();ctx.moveTo(w*.2,cy);ctx.bezierCurveTo(w*.35,cy-80,w*.55,cy+80,w*.8,cy);ctx.stroke();text('music can synchronize multiple senses',18,34)}
 else if(type==='soundscape'){[['danger','#ff9c9c'],['background','#7bdfff'],['anchor','#f8dd94'],['silence','#9ff4cf']].forEach((r,i)=>{ctx.fillStyle=r[1]+'44';ctx.fillRect(30+i*(w-60)/4,80,(w-82)/4,h-142);text(r[0],38+i*(w-60)/4,105,13)});text('soundscape = layers + control + exit',18,34)}
 else if(type==='talkingDrum'){line('#f8dd94',3);ctx.beginPath();for(let x=0;x<w;x++){let y=cy+Math.sin(x*.03+t*4)*24*(1+.65*Math.sin(x*.012+t));if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();text('drum imitates tone contour + rhythm of speech',18,34)}
 else if(type==='theremin'){ctx.fillStyle='rgba(123,223,255,.25)';ctx.fillRect(w*.48,70,12,h-120);let hx=w*(.5+.32*Math.sin(t));ctx.fillStyle='#f8dd94';ctx.beginPath();ctx.arc(hx,cy,22,0,7);ctx.fill();line('#7bdfff',2);for(let i=1;i<5;i++){ctx.beginPath();ctx.arc(w*.5,cy,Math.abs(hx-w*.5)+i*18,0,7);ctx.stroke()}text('hand distance → pitch / volume',18,34)}
 else if(type==='sampler'){for(let i=0;i<12;i++){ctx.fillStyle=i%3?'rgba(123,223,255,.3)':'rgba(255,147,215,.35)';ctx.fillRect(30+i*(w-60)/12,cy-52+Math.sin(i+t)*26,(w-80)/12,104)}text('record → slice → rearrange → new music',18,34)}
 else if(type==='haptic'){for(let i=0;i<7;i++){ctx.fillStyle=`rgba(248,221,148,${.16+.08*Math.sin(t*3+i)})`;ctx.beginPath();ctx.arc(w*.2+i*w*.1,cy,25+10*Math.sin(t*4+i),0,7);ctx.fill()}text('music translated into touch vibration',18,34)}
 else {text(type,18,34)} ctx.restore()}
function drawCosmos(){let c=$('#cosmos');if(!c)return;let ctx=c.getContext('2d');function resize(){c.width=innerWidth*(devicePixelRatio||1);c.height=innerHeight*(devicePixelRatio||1)}resize();addEventListener('resize',resize);let stars=Array.from({length:160},()=>[Math.random(),Math.random(),Math.random()*2.2,Math.random()*6]);function loop(t){let W=c.width,H=c.height;ctx.clearRect(0,0,W,H);let g=ctx.createRadialGradient(W*.5,H*.35,0,W*.5,H*.35,Math.max(W,H)*.8);g.addColorStop(0,'rgba(123,223,255,.10)');g.addColorStop(.42,'rgba(169,140,255,.06)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);stars.forEach(s=>{ctx.globalAlpha=.16+.74*Math.sin(t*.001+s[3])**2;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(s[0]*W,s[1]*H,s[2]*(devicePixelRatio||1),0,7);ctx.fill()});if(!state.lowMotion&&Math.random()<.015){ctx.globalAlpha=.6;ctx.strokeStyle='rgba(248,221,148,.7)';ctx.beginPath();let x=Math.random()*W,y=Math.random()*H*.6;ctx.moveTo(x,y);ctx.lineTo(x+100,y+45);ctx.stroke()}ctx.globalAlpha=1;if(!state.lowMotion)requestAnimationFrame(loop)}requestAnimationFrame(loop)}
Object.assign(window,{setLang,toggleLang,setView,toggleCompact,toggleMotion,openAnimation,closeModal,selectTerm,drawGraph,addXP});drawCosmos();render();
