/* Musicalife: dynamic visual music knowledge app. No external dependencies. */
const $ = (s, root=document)=>root.querySelector(s);
const $$ = (s, root=document)=>Array.from(root.querySelectorAll(s));
const storeKey='musicalife.v1.progress';
const state={view:'home',lang:'ZH',compact:false,lowMotion:false,selectedTerm:null,selectedAnim:'wave',xp:0,done:{},chapter:'overview'};
try{Object.assign(state, JSON.parse(localStorage.getItem(storeKey)||'{}'));}catch(e){}
const save=()=>localStorage.setItem(storeKey, JSON.stringify({lang:state.lang,compact:state.compact,lowMotion:state.lowMotion,xp:state.xp,done:state.done}));

const nav=[
 {id:'home',ico:'✦',cn:'首页',en:'Home'}, {id:'game',ico:'⛵',cn:'声之塔',en:'Odyssey'}, {id:'map',ico:'✧',cn:'知识地图',en:'Map'},
 {id:'voice',ico:'◌',cn:'声乐',en:'Voice'}, {id:'life',ico:'☾',cn:'生活',en:'Life'}, {id:'world',ico:'∞',cn:'探索',en:'World'}
];
const extraNav=[{id:'physics',ico:'∿',cn:'数理',en:'Math'},{id:'library',ico:'☷',cn:'资料',en:'Library'}];
function t(cn,en){return state.lang==='EN'?en:cn}
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
function setView(id){state.view=id; if(location.hash!==`#${id}`) location.hash=id; render();}
window.addEventListener('hashchange',()=>{state.view=location.hash.replace('#','')||'home'; render();});

const categories={
 physics:{cn:'声音物理',en:'Sound physics',color:'#74d7ff'}, ear:{cn:'听觉心理',en:'Psychoacoustics',color:'#9ff3c8'}, theory:{cn:'乐理数理',en:'Music theory',color:'#f6d98b'}, voice:{cn:'声乐人体',en:'Voice body',color:'#ff91d0'}, brain:{cn:'脑科学',en:'Brain',color:'#a68cff'}, life:{cn:'生活应用',en:'Life practice',color:'#ffc37e'}, world:{cn:'语言文化',en:'Culture',color:'#7ae7d6'}, future:{cn:'未来音乐',en:'Future music',color:'#b9a3ff'}
};
const terms=[
 {id:'wave',cat:'physics',cn:'声波',en:'Sound wave',anim:'wave',short:'声音是介质中的压力变化，像一条随时间起伏的曲线。',deep:'音乐的输入首先是物理波：空气压强随时间变化，耳朵把这些变化转成神经信号。',rel:['frequency','amplitude','phase','period'],links:['Open Music Theory|https://viva.pressbooks.pub/openmusictheory/']},
 {id:'frequency',cat:'physics',cn:'频率',en:'Frequency',anim:'wave',short:'频率是每秒振动多少次，通常影响我们听到的高低。',deep:'频率单位是 Hz。音乐里的音高和基频关系密切，但音色、响度、上下文也会影响感知。',rel:['pitch','period','octave','temperament'],links:['Psychoacoustics book|https://link.springer.com/book/10.1007/978-3-540-68888-4']},
 {id:'amplitude',cat:'physics',cn:'振幅',en:'Amplitude',anim:'wave',short:'振幅是波起伏的大小，通常影响声音强弱。',deep:'物理声压不等于主观响度；人耳对不同频率敏感度不同。',rel:['decibel','loudness','dynamicRange'],links:['NIDCD safe listening|https://www.nidcd.nih.gov/health/noise-induced-hearing-loss']},
 {id:'phase',cat:'physics',cn:'相位',en:'Phase',anim:'interference',short:'相位表示波走到周期的哪个位置。',deep:'相位决定叠加时是增强还是抵消，主动降噪和双耳节拍都离不开相位/差异。',rel:['interference','anc','binauralBeat'],links:['Active noise control|https://en.wikipedia.org/wiki/Active_noise_control']},
 {id:'period',cat:'physics',cn:'周期',en:'Period',anim:'metronome',short:'周期是一次完整振动或一次节拍循环需要的时间。',deep:'频率 f 与周期 T 互为倒数。节奏、波形、呼吸都可以看成周期或准周期模式。',rel:['frequency','bpm','rhythmFunction'],links:['Music theory rhythm|https://www.musictheory.net/lessons']},
 {id:'decibel',cat:'physics',cn:'分贝',en:'Decibel',anim:'loudness',short:'分贝是描述声压级的对数量尺。',deep:'分贝不是普通线性单位。增加 10 dB 通常主观上明显更响，长期高音量会增加听力风险。',rel:['amplitude','loudness','safety'],links:['WHO safe listening|https://www.who.int/news-room/questions-and-answers/item/deafness-and-hearing-loss-safe-listening']},
 {id:'spectrum',cat:'physics',cn:'频谱',en:'Spectrum',anim:'harmonics',short:'频谱显示一个声音由哪些频率组成。',deep:'同一个音高因为频谱不同而产生不同音色；这就是为什么钢琴、人声和笛子听起来不一样。',rel:['fundamental','harmonic','timbre','fourier'],links:['Open Music Theory timbre|https://viva.pressbooks.pub/openmusictheory/']},
 {id:'fundamental',cat:'physics',cn:'基频',en:'Fundamental',anim:'harmonics',short:'基频是一个复合音中通常决定音高的最低周期成分。',deep:'歌唱中的 F0 常对应我们听到的音高；泛音结构则塑造音色和明亮度。',rel:['pitch','harmonic','vocalFolds'],links:['NIDCD voice|https://www.nidcd.nih.gov/news/multimedia/how-does-human-body-produce-voice-and-speech-text-version']},
 {id:'harmonic',cat:'physics',cn:'谐波/泛音',en:'Harmonic / overtone',anim:'harmonics',short:'谐波是基频的整数倍，决定音色的光泽和厚度。',deep:'f、2f、3f、4f 叠加，声音会从纯音变成更接近乐器或人声。合唱和共鸣都与谐波能量有关。',rel:['spectrum','fourier','timbre','choir'],links:['This Is Your Brain on Music|https://www.penguinrandomhouse.com/books/296122/this-is-your-brain-on-music-by-daniel-j-levitin/']},
 {id:'fourier',cat:'physics',cn:'傅里叶思想',en:'Fourier idea',anim:'fourier',short:'复杂声音可以拆成许多简单正弦波。',deep:'这是“音乐像数学一样美”的核心入口：一个复杂音色可以看作一组频率、振幅、相位的组合。',rel:['spectrum','harmonic','sampling','synth'],links:['Fourier transform intro|https://betterexplained.com/articles/an-interactive-guide-to-the-fourier-transform/']},
 {id:'resonance',cat:'physics',cn:'共振',en:'Resonance',anim:'resonance',short:'某个空间或物体特别容易响应某些频率，于是声音被放大。',deep:'乐器腔体、房间、口腔咽腔都具有共振特性。唱歌不是把声音“塞进腔体”，而是调节声道形状，改变哪些频率被增强。',rel:['standingWave','formant','chambers','instrumentBody'],links:['Science of Singing Voice|https://www.cornellpress.cornell.edu/book/9780875805429/the-science-of-the-singing-voice/']},
 {id:'standingWave',cat:'physics',cn:'驻波',en:'Standing wave',anim:'resonance',short:'波在边界间反射叠加，形成固定的波峰波谷。',deep:'弦乐、管乐、房间声学都可以用驻波理解。空间太小或太硬会让某些频率异常突出。',rel:['resonance','instrumentBody','roomMode'],links:['Acoustics basics|https://www.acousticslab.org/']},
 {id:'beatFreq',cat:'physics',cn:'拍频',en:'Beat frequency',anim:'beat',short:'两个接近频率同时出现，会听到忽强忽弱的摆动。',deep:'调音时常用拍频判断两个音是否接近；频率越接近，拍动越慢。',rel:['interference','binauralBeat','tuning'],links:['Music theory tuning|https://www.musictheory.net/lessons']},
 {id:'masking',cat:'ear',cn:'掩蔽效应',en:'Masking',anim:'masking',short:'一个声音会盖住另一个声音，尤其当频率接近或噪声更强时。',deep:'白噪声/粉红噪声帮助睡眠或专注，通常不是“治愈频率”，而是用稳定声音盖住不可预测噪声。',rel:['criticalBand','noiseColor','sleep','adhd'],links:['Psychoacoustics|https://link.springer.com/book/10.1007/978-3-540-68888-4']},
 {id:'criticalBand',cat:'ear',cn:'临界带',en:'Critical band',anim:'criticalBand',short:'人耳把相近频率放在类似“频率通道”里处理。',deep:'两个声音太靠近时更容易互相干扰，粗糙、不清楚、被盖住都可由此解释。',rel:['masking','roughness','jnd'],links:['Psychoacoustics|https://link.springer.com/book/10.1007/978-3-540-68888-4']},
 {id:'jnd',cat:'ear',cn:'最小可觉差 JND',en:'Just noticeable difference',anim:'jnd',short:'刚刚能被听出来的最小变化。',deep:'音高、响度、时间都有 JND。训练耳朵就是逐渐提高对细小差异的辨认。',rel:['pitch','loudness','earTraining'],links:['musictheory.net exercises|https://www.musictheory.net/exercises']},
 {id:'roughness',cat:'ear',cn:'粗糙度',en:'Roughness',anim:'roughness',short:'相近频率快速互相干扰时，会产生刺耳、毛躁的感觉。',deep:'不协和、警报声、某些噪声让人烦躁，常和粗糙度/波动强度有关。',rel:['criticalBand','dissonance','sensoryOverload'],links:['Psychoacoustics|https://link.springer.com/book/10.1007/978-3-540-68888-4']},
 {id:'binaural',cat:'ear',cn:'双耳效应',en:'Binaural effect',anim:'binaural',short:'两只耳朵收到声音的时间差和强度差帮助定位。',deep:'耳机空间音频、声景设计、双耳去掩蔽，都利用左右耳差异来增强方向感和分离度。',rel:['spatialAudio','binauralBeat','anc','soundscape'],links:['Interaural difference|https://pressbooks.umn.edu/sensationandperception/chapter/interaural-level-difference-draft/']},
 {id:'binauralBeat',cat:'ear',cn:'双耳节拍',en:'Binaural beat',anim:'binauralBeat',short:'左右耳分别听到接近频率时，大脑感到一个差频节拍。',deep:'它适合作为探索性声音体验，但证据差异大，不能写成确定疗法。',rel:['beatFreq','phase','brainwave'],links:['Review on binaural beats|https://pmc.ncbi.nlm.nih.gov/articles/PMC10198548/']},
 {id:'anc',cat:'ear',cn:'主动降噪 ANC',en:'Active noise control',anim:'anc',short:'用反相声音抵消部分噪声，尤其适合稳定低频。',deep:'ANC 对飞机/地铁低频更有效，对突发人声和高频较难。理解它能帮助正确选择耳机和声景策略。',rel:['phase','interference','masking'],links:['Active noise control|https://en.wikipedia.org/wiki/Active_noise_control']},
 {id:'pitch',cat:'theory',cn:'音高',en:'Pitch',anim:'pitchStair',short:'音高是人对声音高低的感知。',deep:'音高通常由基频决定，但不是频率的简单复制；音色、响度和上下文都会影响音高判断。',rel:['frequency','scale','relativePitch','absolutePitch'],links:['musictheory.net notes|https://www.musictheory.net/lessons']},
 {id:'interval',cat:'theory',cn:'音程',en:'Interval',anim:'pitchStair',short:'音程是两个音之间的距离。',deep:'相对音准训练的核心是听出音程，如大三度、纯五度、八度。',rel:['relativePitch','scale','chord'],links:['musictheory.net intervals|https://www.musictheory.net/lessons']},
 {id:'scale',cat:'theory',cn:'音阶',en:'Scale',anim:'pitchStair',short:'音阶是按规则排列的一组音。',deep:'半音、全音、八度、调式都在音阶里相遇。音阶不是死记表格，而是一组“可返回的路径”。',rel:['temperament','mode','tonality','solfege'],links:['Open Music Theory scales|https://viva.pressbooks.pub/openmusictheory/']},
 {id:'temperament',cat:'theory',cn:'十二平均律',en:'Equal temperament',anim:'temperament',short:'把八度均分成 12 个相等半音。',deep:'每个半音频率比例相同，约等于 2^(1/12)。它让转调更方便，但牺牲了某些纯净频率比。',rel:['octave','scale','tuning'],links:['Open Music Theory tuning|https://viva.pressbooks.pub/openmusictheory/']},
 {id:'relativePitch',cat:'theory',cn:'相对音准',en:'Relative pitch',anim:'earTraining',short:'根据参照音判断音程和旋律距离。',deep:'大多数音乐学习最实用的是相对音准：能听出旋律如何移动、和弦如何变化。',rel:['interval','scale','earTraining'],links:['musictheory.net ear training|https://www.musictheory.net/exercises']},
 {id:'absolutePitch',cat:'theory',cn:'绝对音准',en:'Absolute pitch',anim:'earTraining',short:'没有参照音也能说出音名。',deep:'绝对音准罕见且不等于音乐能力。相对音准、节奏感和表达力对大多数人更重要。',rel:['pitch','relativePitch','memory'],links:['This Is Your Brain on Music|https://www.penguinrandomhouse.com/books/296122/this-is-your-brain-on-music-by-daniel-j-levitin/']},
 {id:'rhythm',cat:'theory',cn:'节奏',en:'Rhythm',anim:'metronome',short:'节奏是声音在时间中的组织。',deep:'节奏连接身体、注意和预测。它不只是“快慢”，还包括重音、细分、切分和律动。',rel:['bpm','meter','syncopation','entrainment'],links:['Open Music Theory rhythm|https://viva.pressbooks.pub/openmusictheory/']},
 {id:'bpm',cat:'theory',cn:'BPM / 节拍器',en:'BPM / metronome',anim:'metronome',short:'BPM 表示每分钟多少拍。',deep:'节拍器不是为了机械化，而是建立内部时间感。先跟拍，再练细分、弱拍、静音小节。',rel:['rhythm','meter','adhd','movement'],links:['Metronome practice|https://www.musictheory.net/lessons']},
 {id:'syncopation',cat:'theory',cn:'切分',en:'Syncopation',anim:'syncopation',short:'把重音放到意料之外的位置。',deep:'切分制造身体想动的张力：你以为重音要来，音乐偏偏绕开或提前。',rel:['rhythm','prediction','groove'],links:['Open Music Theory rhythm|https://viva.pressbooks.pub/openmusictheory/']},
 {id:'polyrhythm',cat:'theory',cn:'复节奏',en:'Polyrhythm',anim:'polyrhythm',short:'两个或多个节奏周期同时进行。',deep:'例如 3 对 2。复节奏让音乐像多条时间河流交织，常见于非洲鼓乐、极简音乐和现代音乐。',rel:['rhythm','talkingDrum','gamelan'],links:['Open Music Theory rhythm|https://viva.pressbooks.pub/openmusictheory/']},
 {id:'chord',cat:'theory',cn:'和弦',en:'Chord',anim:'chord',short:'多个音同时响起，形成稳定、明亮、紧张或悬浮的感觉。',deep:'do-mi-sol 是最直观的和弦积木。合唱就是让不同人声组成活的和声。',rel:['harmony','interval','choir'],links:['Open Music Theory harmony|https://viva.pressbooks.pub/openmusictheory/']},
 {id:'harmony',cat:'theory',cn:'和声',en:'Harmony',anim:'harmony',short:'和声是音与音同时或连续组织出的关系。',deep:'和声让音乐有方向：紧张、停留、解决、回家。',rel:['chord','tonality','prediction','emotion'],links:['Open Music Theory|https://viva.pressbooks.pub/openmusictheory/']},
 {id:'vocalFolds',cat:'voice',cn:'声带',en:'Vocal folds',anim:'vocalFold',short:'声带是喉部两片柔软组织，气流通过时开合振动。',deep:'唱歌的音高、音色、健康都与声带振动方式有关。不能靠挤压解决音准或高音。',rel:['airflow','closure','sourceFilter','pitch'],links:['NIDCD voice|https://www.nidcd.nih.gov/news/multimedia/how-does-human-body-produce-voice-and-speech-text-version']},
 {id:'airflow',cat:'voice',cn:'气流',en:'Airflow',anim:'vocalFold',short:'从肺部出来的空气是人声的动力。',deep:'好声音不是吸超多气，而是稳定、可控、不过量的呼气。',rel:['subglottal','breathSupport','vocalFolds'],links:['NATS resources|https://www.nats.org/Music_Theater_-_Resources.html']},
 {id:'subglottal',cat:'voice',cn:'声门下压',en:'Subglottal pressure',anim:'vocalFold',short:'声带下方空气压力推动声带振动。',deep:'压力不足会虚，压力过大容易挤。训练目标是压力、气流、闭合的平衡。',rel:['airflow','closure','breathSupport'],links:['Science of Singing Voice|https://www.cornellpress.cornell.edu/book/9780875805429/the-science-of-the-singing-voice/']},
 {id:'closure',cat:'voice',cn:'声带闭合',en:'Vocal fold closure',anim:'vocalFold',short:'声带闭合太松会漏气，太紧会挤压。',deep:'平衡闭合让声音清楚、可持续。起声、音色、疲劳都与闭合方式有关。',rel:['onset','sovt','vocalHealth'],links:['NIDCD voice|https://www.nidcd.nih.gov/health/taking-care-your-voice']},
 {id:'sovt',cat:'voice',cn:'SOVT 半闭合声道',en:'SOVT',anim:'sovt',short:'吸管音、唇颤、哼鸣等让出口变窄，帮助声带更省力。',deep:'半闭合声道产生一点回压，常用于声乐热身和嗓音训练。',rel:['closure','airflow','vocalHealth'],links:['SOVT study|https://pmc.ncbi.nlm.nih.gov/articles/PMC4610291/']},
 {id:'chambers',cat:'voice',cn:'三腔/共鸣澄清',en:'Resonance chambers',anim:'chambers',short:'胸腔、口腔、头腔是常用感觉词，但声学上要区分感觉和真实滤波。',deep:'口腔、咽腔、鼻腔直接改变声道滤波；胸腔更多是体感振动，头腔更多是高频和声区感觉。',rel:['resonance','formant','sourceFilter'],links:['Source-filter theory|https://pmc.ncbi.nlm.nih.gov/articles/PMC2757425/']},
 {id:'sourceFilter',cat:'voice',cn:'声源-滤波理论',en:'Source-filter theory',anim:'formant',short:'声带产生声源，声道像滤波器改变音色。',deep:'这是理解共鸣、元音、声区、唱法的关键模型。',rel:['vocalFolds','formant','vowel','resonance'],links:['Source-filter interaction|https://pmc.ncbi.nlm.nih.gov/articles/PMC2757425/']},
 {id:'formant',cat:'voice',cn:'共振峰 Formant',en:'Formant',anim:'formant',short:'声道特别放大的频率区域。',deep:'不同元音有不同 F1/F2 模式。歌唱中的明亮、圆润、穿透常和共振峰调节有关。',rel:['vowel','resonance','chambers'],links:['Science of Singing Voice|https://www.cornellpress.cornell.edu/book/9780875805429/the-science-of-the-singing-voice/']},
 {id:'vowel',cat:'voice',cn:'元音地图',en:'Vowel map',anim:'formant',short:'a/e/i/o/u 是声道形状的不同配置。',deep:'口腔开合、舌位前后、圆唇程度共同决定元音和音色。',rel:['formant','articulation','sourceFilter'],links:['NIDCD speech|https://www.nidcd.nih.gov/health/speech-and-language']},
 {id:'articulation',cat:'voice',cn:'吐字',en:'Articulation',anim:'articulation',short:'唇、齿、舌、软腭把声音塑造成语言。',deep:'吐字不是把每个字咬死，而是在气流连续中让语言清楚。',rel:['vowel','prosody','languageTone'],links:['NIDCD speech|https://www.nidcd.nih.gov/health/speech-and-language']},
 {id:'languageTone',cat:'voice',cn:'声调/调值',en:'Tone contour',anim:'toneContour',short:'声调是语言中有意义的音高走势。',deep:'普通话四声、粤语声调、约鲁巴语和会说话的鼓都说明讲话本身也是音乐。',rel:['prosody','talkingDrum','pitch'],links:['Tone language neuroscience|https://www.frontiersin.org/journals/neuroscience/articles/10.3389/fnins.2018.00495/full']},
 {id:'prosody',cat:'voice',cn:'语调/韵律',en:'Prosody',anim:'prosody',short:'语调、重音、停顿、速度让一句话产生情绪和关系。',deep:'同一句话可以因为音高线和停顿不同而变成安慰、命令、玩笑或质问。',rel:['languageTone','rhythm','socialVoice'],links:['NIDCD speech|https://www.nidcd.nih.gov/health/speech-and-language']},
 {id:'prediction',cat:'brain',cn:'预测编码',en:'Predictive coding',anim:'bayes',short:'大脑不断预测下一刻声音，再根据误差更新理解。',deep:'音乐的美常在“可预测”和“有惊喜”之间。转折太少会无聊，太多会混乱。',rel:['rhythm','melody','dopamine','bayes'],links:['Predictive coding music rhythm|https://pmc.ncbi.nlm.nih.gov/articles/PMC4181238/']},
 {id:'entrainment',cat:'brain',cn:'节律夹带',en:'Entrainment',anim:'metronome',short:'身体和神经活动会与外部节律同步。',deep:'走路、呼吸、拍手、合唱、康复训练都可以利用节律夹带。',rel:['bpm','movement','rehab','adhd'],links:['Neural entrainment|https://pmc.ncbi.nlm.nih.gov/articles/PMC6769420/']},
 {id:'dmn',cat:'brain',cn:'默认模式网络 DMN',en:'Default mode network',anim:'dmn',short:'与自我、回忆、想象、内心叙事相关的大脑网络。',deep:'熟悉、忧伤或叙事性音乐可能带动回忆和内向注意。',rel:['memory','emotion','mindfulness'],links:['Music and DMN|https://www.nature.com/articles/s41598-017-14849-0']},
 {id:'dopamine',cat:'brain',cn:'奖赏系统/多巴胺',en:'Reward / dopamine',anim:'reward',short:'音乐期待、高潮和解决会激活奖赏相关系统。',deep:'喜欢的音乐不是“玄学治愈”，它和预测、记忆、身体反应、意义共同构成奖赏体验。',rel:['prediction','emotion','motivation'],links:['Music reward|https://www.nature.com/articles/nn.2726']},
 {id:'hrv',cat:'brain',cn:'HRV 心率变异性',en:'Heart rate variability',anim:'multisensory',short:'心跳间隔的微小变化，常作为自主神经调节指标之一。',deep:'慢呼气、哼鸣、低唤醒音乐、正念可能帮助身体降档，但需要个体化。',rel:['vagus','breathing','mindfulness'],links:['HRV overview|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5624990/']},
 {id:'vagus',cat:'brain',cn:'迷走神经',en:'Vagus nerve',anim:'multisensory',short:'连接脑干和内脏调节系统，与呼吸、心率、放松有关。',deep:'延长呼气、哼鸣、唱歌和节律化呼吸可能通过身体路径支持稳定。',rel:['hrv','breathing','singingHealth'],links:['NIDCD voice|https://www.nidcd.nih.gov/health/taking-care-your-voice']},
 {id:'sleep',cat:'life',cn:'睡眠声音策略',en:'Sleep sound strategy',anim:'masking',short:'低信息量、低动态、可忽略的声音可以帮助睡前降档。',deep:'睡前不需要“好听”，而需要低预测负荷、低突发、低歌词负荷和安全感。',rel:['masking','noiseColor','mindfulness'],links:['Music and sleep review|https://pmc.ncbi.nlm.nih.gov/articles/PMC11536203/']},
 {id:'adhd',cat:'life',cn:'ADHD 启动',en:'ADHD activation',anim:'metronome',short:'稳定节律可以作为外部执行功能支架。',deep:'启动时常需要 90–120 BPM、稳定鼓点、短时承诺；进入深工后再降信息量。',rel:['bpm','entrainment','rhythm'],links:['Music attention study|https://www.nature.com/articles/s41598-024-60218-z']},
 {id:'pain',cat:'life',cn:'疼痛管理辅助',en:'Pain support',anim:'painGate',short:'音乐可通过注意、情绪、呼吸和可控感辅助疼痛管理。',deep:'它不是替代医疗，而是可能作为疼痛管理中的一个辅助自我调节工具。',rel:['attention','breathing','emotion','mindfulness'],links:['Music therapy pain review|https://www.cochrane.org/CD004843/SYMPT_music-therapy-for-pain-relief']},
 {id:'mindfulness',cat:'life',cn:'音乐正念 / MBCT',en:'Music mindfulness / MBCT',anim:'mindfulness',short:'不是评价音乐好坏，而是观察声音、身体和注意力如何变化。',deep:'听见—注意跑走—温柔回来，是音乐正念的核心练习。',rel:['dmn','hrv','sleep','emotion'],links:['MBCT overview|https://www.nccih.nih.gov/health/meditation-and-mindfulness-effectiveness-and-safety']},
 {id:'soundscape',cat:'life',cn:'声景设计',en:'Soundscape design',anim:'soundscape',short:'声景不是分贝数，而是人在情境中如何体验声音。',deep:'感官友好空间需要危险提示、背景底噪、安全锚点、静音出口和控制权。',rel:['masking','binaural','acousticEcology'],links:['ISO soundscape|https://www.iso.org/obp/ui/#iso:std:iso:12913:-1:ed-1:v1:en']},
 {id:'talkingDrum',cat:'world',cn:'会说话的鼓',en:'Talking drum',anim:'talkingDrum',short:'某些鼓能模仿声调语言的音高和节奏。',deep:'约鲁巴 dùndún 鼓展示了语言、声调、节奏、社会沟通如何交织。',rel:['languageTone','polyrhythm','worldMusic'],links:['Talking drum study|https://pmc.ncbi.nlm.nih.gov/articles/PMC8173200/']},
 {id:'gamelan',cat:'world',cn:'甘美兰',en:'Gamelan',anim:'gamelan',short:'印尼金属打击乐合奏，层叠节奏与音色极具空间感。',deep:'它提醒我们：音乐不只有西方和声逻辑，也可以是时间层、音色层和群体互动。',rel:['polyrhythm','timbre','worldMusic'],links:['Gamelan overview|https://en.wikipedia.org/wiki/Gamelan']},
 {id:'theremin',cat:'future',cn:'Theremin 特雷门琴',en:'Theremin',anim:'theremin',short:'不用接触，通过手与电磁场控制音高和音量。',deep:'它像科幻里的歌声：连续音高、无接触演奏、身体动作转译成声音。',rel:['pitch','electronicInstrument','sciFi'],links:['Theremin history|https://www.britannica.com/art/theremin']},
 {id:'sampling',cat:'future',cn:'采样器',en:'Sampler',anim:'sampler',short:'把已有声音切片、重排、变调，生成新音乐。',deep:'采样让音乐媒介变成可编辑材料，也连接记忆、文化再创作和电子音乐。',rel:['fourier','mediaHistory','electronicInstrument'],links:['Sampling overview|https://en.wikipedia.org/wiki/Sampling_(music)']},
 {id:'haptic',cat:'future',cn:'触觉音乐',en:'Haptic music',anim:'haptic',short:'把音乐转成身体可感到的振动。',deep:'触觉音乐让听觉障碍者、舞者、游戏和沉浸式装置都能用身体接收音乐结构。',rel:['multisensory','futureMusic','accessibility'],links:['Haptic music research|https://dl.acm.org/keyword/haptic%20music']}
];
terms.forEach((x,i)=>{x.x=(i%8)*120+90; x.y=Math.floor(i/8)*86+70});
const termMap=Object.fromEntries(terms.map(x=>[x.id,x]));

const anims=[
 ['wave','声波函数','Sound wave'],['harmonics','谐波叠加','Harmonics'],['resonance','共振管','Resonance'],['fourier','傅里叶频谱','Fourier spectrum'],['masking','掩蔽效应','Masking'],['binaural','双耳定位','Binaural location'],['binauralBeat','双耳节拍','Binaural beat'],['anc','ANC 反相波','ANC wave'],['pitchStair','音阶楼梯','Scale stair'],['metronome','节拍器与细分','Metronome'],['syncopation','切分','Syncopation'],['polyrhythm','复节奏','Polyrhythm'],['chord','和弦积木','Chord blocks'],['vocalFold','声带门','Vocal folds'],['sovt','SOVT 回压','SOVT'],['chambers','三腔共鸣澄清','Chambers'],['formant','元音 Formant','Formants'],['toneContour','声调曲线','Tone contour'],['choir','合唱和声','Choir harmony'],['multisensory','多感官同步','Multisensory'],['painGate','疼痛调节','Pain support'],['soundscape','声景房间','Soundscape'],['talkingDrum','会说话的鼓','Talking drum'],['theremin','特雷门琴','Theremin'],['sampler','采样器切片','Sampler'],['haptic','触觉音乐','Haptic music']
];

const voiceChapters=[
 {id:'overview',cn:'总模型',en:'Model',anim:'vocalFold',body:['输入：身体能量 + 空气；动力：肺部气流；振动：声带开合；塑形：咽腔、口腔、鼻腔、唇舌齿；输出：语音、歌声、音色、情绪。','先理解输入和输出，练声才不会变成只靠嗓子用力。'],practice:['用手轻放肋骨，吸气时感受肋骨微微展开。','轻轻说“嗯—啊”，观察声音从闭口到开口如何变化。']},
 {id:'air',cn:'气流与声门下压',en:'Airflow',anim:'vocalFold',body:['气息不是吸很多气，而是稳定气流。声门下压推动声带振动，太少会虚，太多会挤。','高音不靠硬推气，而靠气流、闭合、声道形状协同。'],practice:['sss 8 秒：气流稳定，不抖。','vvv 5 秒：加入声带振动。','一句话练习：一口气说完整句，不憋、不挤。']},
 {id:'folds',cn:'声带闭合与起声',en:'Closure',anim:'vocalFold',body:['声带像一扇柔软的门。太松：漏气；太紧：挤压；平衡：清楚、可持续。','起声分气声起、硬起、平衡起。初学目标是轻柔而清楚。'],practice:['嗯—嗯—嗯，像轻轻点亮灯。','ng—啊，保持喉咙不突然用力。','唱完如果痛、哑、刺，停止。']},
 {id:'sovt',cn:'SOVT 半闭合声道',en:'SOVT',anim:'sovt',body:['吸管音、唇颤、舌颤、哼鸣、v/z 都是友好的入口。','出口变窄产生回压，帮助声带更稳定省力。'],practice:['吹吸管 5 秒，不发声。','吸管发 wu 5 秒。','吸管滑音：低—高—低。','拿掉吸管唱 u-o-a。']},
 {id:'resonance',cn:'三腔/共鸣/共振',en:'Resonance',anim:'chambers',body:['胸腔、口腔、头腔常是感觉词。真实声学中，咽腔、口腔、鼻腔通过声道滤波改变音色。','胸腔更多是体感振动；头腔更多是高频/声区感觉；口腔和咽腔是真正影响元音和明暗的重要空间。'],practice:['m—mi—me—ma—mo—mu，感受音色变化。','不要追求“声音放到哪里”，先观察嘴型和舌位如何改变声音。']},
 {id:'formant',cn:'Formant 与元音地图',en:'Formants',anim:'formant',body:['声带产生原始声音，声道像滤波器。Formant 是被放大的频率区。','/a/ 开放，/i/ 明亮，/u/ 圆暗；元音是唱歌音色控制的核心。'],practice:['同一个音高唱 i-e-a-o-u。','保持音高不变，只改变嘴型，听音色变化。']},
 {id:'articulation',cn:'吐字与语言音乐性',en:'Articulation',anim:'toneContour',body:['讲话也是音乐：音高、节奏、停顿、重音、语气都在表达意义。','声调语言中，调值本身就是词义的一部分。'],practice:['同一句“我在这里”说成：平静、疑问、安慰、生气、讲故事。','观察音高线、速度、停顿怎样改变意思。']},
 {id:'pitch',cn:'音高、音准、调值',en:'Pitch',anim:'pitchStair',body:['绝对音准是不用参照物认音名；相对音准是听音程距离。多数人更需要相对音准。','调值是语言或旋律中的音高高度与走势系统。'],practice:['先滑音，不急着唱准。','唱 sol-mi-do，再唱 do-re-mi-fa-sol。','用手机钢琴 App 给一个参照音，练听上行/下行。']},
 {id:'rhythm',cn:'节拍器与节奏',en:'Rhythm',anim:'metronome',body:['节拍器不是让你机械，而是建立内部时间感。','节奏包括 BPM、重拍、弱拍、细分、切分、复节奏。'],practice:['60 BPM 拍手 1 分钟。','每 4 拍强调第 1 拍。','一拍分成 2 个，再分成 3 个。','静音 4 小节再回来检查。']},
 {id:'choir',cn:'合唱、和声与共振',en:'Choir',anim:'choir',body:['合唱不是每个人更大声，而是声部之间建立频率关系、音色平衡和呼吸同步。','do-mi-sol 叠加会产生稳定和声；频率接近会产生拍频，调音时可听到波动。'],practice:['一个人唱 do，另一个人唱 mi，再加入 sol。','听稳定感、明亮感、紧张感如何出现。']},
 {id:'style',cn:'风格与表达',en:'Style',anim:'prosody',body:['流行、美声、音乐剧、戏曲、rap、吟唱都是不同身体策略、声学策略与文化表达。','没有唯一正确声音；关键是健康、清楚、可持续、有表达。'],practice:['同一句歌词先说，再唱，再换风格：轻声、讲述、戏剧、节奏说唱。']},
 {id:'health',cn:'嗓音健康',en:'Vocal health',anim:'sovt',body:['疼痛、沙哑、刺痛、唱完失声不是正常训练反馈。','长期嘶哑、吞咽困难、呼吸困难、疼痛需要耳鼻喉科或言语治疗师评估。'],practice:['练习 5 分钟后做 30 秒哼鸣放松。','喝水、降低音量、减少连续大声讲话。']}
];
const lifeCards=[
 {cn:'睡前脑内噪声',en:'Bedtime mental noise',anim:'masking',problem:'脑子停不下来，环境声又让人警觉。',mechanism:'低动态、低歌词负荷的声音降低预测负担；粉红噪声/雨声可掩蔽不可预测背景声。',steps:['关掉歌词和短视频。','选择粉红噪声、雨声、低动态 ambient。','音量小到刚好盖住环境声。','10 分钟后再降低音量。'],avoid:'不要用过于激动、旋律起伏太大的音乐强行催眠。',links:['Music and sleep review|https://pmc.ncbi.nlm.nih.gov/articles/PMC11536203/']},
 {cn:'ADHD 启动困难',en:'ADHD activation',anim:'metronome',problem:'知道要做，但身体和注意力启动不了。',mechanism:'稳定节律提供外部时间支架，降低启动门槛。',steps:['选 90–120 BPM 稳定节奏。','只承诺开始 3 分钟。','开始后切换到低信息量音乐。','任务结束用短音乐奖励。'],avoid:'不要一开始就放复杂歌词或情绪过强的音乐。',links:['Music and attention|https://www.nature.com/articles/s41598-024-60218-z']},
 {cn:'ASD / 感官过载',en:'Sensory overload',anim:'soundscape',problem:'突发声、人声、设备噪声让身体进入警戒。',mechanism:'降低突发、降低粗糙度、增加可预测声音和退出权。',steps:['先停止刺激，不急着加音乐。','选择单调、可预测、可停止的声音。','用温和掩蔽，不用大声盖过去。','设计静音角落和耳机方案。'],avoid:'不要把“播放疗愈音乐”当成唯一解决。',links:['WHO environmental noise|https://www.who.int/tools/compendium-on-health-and-environment/environmental-noise']},
 {cn:'疼痛管理辅助',en:'Pain support',anim:'painGate',problem:'疼痛让注意力锁定在身体上。',mechanism:'音乐可辅助注意转移、情绪调节、呼吸同步和可控感。',steps:['选择熟悉、安全的音乐。','跟着音乐延长呼气。','把注意力放到节奏或低音上。','记录疼痛强度前后变化。'],avoid:'不能替代医疗；新发剧痛或异常症状必须就医。',links:['Cochrane music therapy pain|https://www.cochrane.org/CD004843/SYMPT_music-therapy-for-pain-relief']},
 {cn:'记忆学习',en:'Memory learning',anim:'pitchStair',problem:'内容难记、流程混乱。',mechanism:'旋律、节奏和押韵给记忆加索引；情绪意义增强编码。',steps:['把知识拆成短句。','加入固定节奏。','给重点词设置旋律高点。','重复时逐渐去掉音乐提示。'],avoid:'阅读理解时避免歌词抢占语言工作记忆。',links:['This Is Your Brain on Music|https://www.penguinrandomhouse.com/books/296122/this-is-your-brain-on-music-by-daniel-j-levitin/']},
 {cn:'情绪低落',en:'Low mood',anim:'prediction',problem:'听快乐音乐反而烦，觉得被强迫开心。',mechanism:'Iso principle：先匹配情绪，再轻微上移。',steps:['先选接近当前情绪的音乐。','2–3 首后换稍微明亮一点。','加入哼唱或轻微移动。','最后用一首稳定收束。'],avoid:'不要一开始用强烈快乐音乐压过真实情绪。',links:['AMTA music therapy|https://www.musictherapy.org/about/musictherapy/']},
 {cn:'焦虑/自主神经失调',en:'Anxiety / autonomic',anim:'multisensory',problem:'心跳快、呼吸浅、身体紧。',mechanism:'慢节律、延长呼气、哼鸣和低动态音乐可作为降档入口。',steps:['选择 60–80 BPM 或无明显节拍 ambient。','用 4 秒吸、6–8 秒呼。','轻哼 mmm 30 秒。','记录心跳、呼吸和紧张程度。'],avoid:'头晕、胸痛、恐慌加重时停止并寻求帮助。',links:['NCCIH mindfulness|https://www.nccih.nih.gov/health/meditation-and-mindfulness-effectiveness-and-safety']},
 {cn:'音乐正念 / MBCT',en:'Music mindfulness',anim:'mindfulness',problem:'注意力总是被情绪和念头带走。',mechanism:'把声音当作锚点，训练注意跑走后温柔回来。',steps:['听 1 分钟一个持续声音。','标记：听到、想到、身体感觉。','注意跑走时回到声音消失处。','结束后写一句观察。'],avoid:'不要评价自己“做得好不好”。',links:['NCCIH mindfulness|https://www.nccih.nih.gov/health/meditation-and-mindfulness-effectiveness-and-safety']},
 {cn:'社交声音困难',en:'Social voice',anim:'toneContour',problem:'别人觉得语气冷、急、太大声或不合场景。',mechanism:'语调、重音、停顿和音量共同构成社交信息。',steps:['一句话录 4 个版本：友好/坚定/疑问/安慰。','看哪里升高、哪里停顿。','练习降低音量但保留清楚度。','用短句和停顿给对方反应空间。'],avoid:'不要把声音训练变成伪装自己；目标是选择权。',links:['NIDCD speech|https://www.nidcd.nih.gov/health/speech-and-language']},
 {cn:'嗓音疲劳',en:'Vocal fatigue',anim:'sovt',problem:'讲话或唱歌后喉咙累、哑、紧。',mechanism:'声带负荷、闭合过紧、干燥和音量过大都会增加疲劳。',steps:['停止大声说话。','吸管音/哼鸣 30 秒。','补水，降低环境噪声。','连续嘶哑超过两周要检查。'],avoid:'不要用清嗓和硬喊解决。',links:['NIDCD taking care of voice|https://www.nidcd.nih.gov/health/taking-care-your-voice']}
];
const instruments=[
 ['古琴','Guqin','弦振动','Strings','长弦、泛音、滑音，像时间在木头中流动。','resonance'],['Kora','Kora','弦振动','Strings','西非竖琴-鲁特，复杂拨弦图案像流动的河。','polyrhythm'],['Hurdy-gurdy','Hurdy-gurdy','轮擦弦','Wheel strings','用转轮摩擦琴弦，像古老机械风琴与提琴的混合。','resonance'],['尺八','Shakuhachi','空气柱','Air column','气息、噪声和音高之间有极细腻的边界。','airflow'],['管风琴','Pipe organ','空气柱','Air column','建筑本身变成乐器，管长决定频率。','standingWave'],['Dùndún','Talking drum','膜振动','Membrane','用鼓皮张力模仿声调语言。','talkingDrum'],['Tabla','Tabla','膜振动','Membrane','印度鼓语系统，节奏像可说出的语言。','polyrhythm'],['Mbira','Mbira','自鸣体','Idiophone','金属簧片振动，循环图案产生梦境般和声。','harmonic'],['Gamelan','Gamelan','自鸣体','Idiophone','金属音色、层叠节奏、群体时间感。','gamelan'],['Handpan','Handpan','自鸣体','Idiophone','一个金属壳体上有多个调音区域，适合冥想和即兴。','resonance'],['Theremin','Theremin','电子振荡','Electronic','不用触碰，手势改变电磁场控制音高和音量。','theremin'],['Ondes Martenot','Ondes Martenot','电子乐器','Electronic','早期电子乐器，声音像幽灵、歌唱和科幻光线。','theremin'],['模块合成器','Modular synth','电子振荡','Electronic','用电压连接振荡器、滤波器、包络，像搭建声音宇宙。','fourier'],['采样器','Sampler','媒介乐器','Media instrument','把现实声音切片、变调、重排。','sampler'],['触觉乐器','Haptic instruments','未来乐器','Future','把声音转成身体可感的振动地图。','haptic']
];
const timeline=[
 ['身体与口传','Body & oral tradition','音乐最早不只是作品，而是身体、劳动、仪式、记忆。'],['骨笛/鼓','Bone flutes & drums','材料开始保存声音动作。'],['记谱','Notation','声音被写下，音乐跨越身体和时间。'],['宗教空间','Sacred space','建筑回声塑造唱法和音乐形式。'],['剧场与歌剧','Theatre & opera','声音、叙事、空间、身体联合成大型系统。'],['唱片','Recording','音乐从现场事件变成可复制媒介。'],['广播','Radio','声音进入公共生活和家庭空间。'],['磁带','Tape','剪辑、倒放、拼贴让声音可塑。'],['合成器','Synthesizer','电路生成音色，声音成为可设计对象。'],['采样器','Sampler','世界声音成为可重组材料。'],['DAW','DAW','音乐制作进入可视化时间线。'],['流媒体','Streaming','推荐系统改变我们遇见音乐的方式。'],['AI / 触觉 / 太空','AI / haptic / space','音乐可能变成个体化、多感官、跨星际媒介。']
];
const books=[
 ['Fastl & Zwicker','Psychoacoustics: Facts and Models','心理声学基础：掩蔽、响度、粗糙度、双耳听觉、音乐声学。','https://link.springer.com/book/10.1007/978-3-540-68888-4'],
 ['Daniel Levitin','This Is Your Brain on Music','音乐、大脑、记忆、奖赏与人类迷恋音乐的入门。','https://www.penguinrandomhouse.com/books/296122/this-is-your-brain-on-music-by-daniel-j-levitin/'],
 ['David Huron','Sweet Anticipation','音乐期待心理学：为什么“下一步”让人着迷。','https://direct.mit.edu/books/monograph/1961/Sweet-AnticipationMusic-and-the-Psychology-of'],
 ['Johan Sundberg','The Science of the Singing Voice','声乐科学：声源、声道、共鸣、歌唱声学。','https://www.cornellpress.cornell.edu/book/9780875805429/the-science-of-the-singing-voice/'],
 ['Open Music Theory','Open online textbook','开放乐理教材：音阶、节奏、和声、曲式、流行与爵士。','https://viva.pressbooks.pub/openmusictheory/'],
 ['musictheory.net','Lessons and exercises','乐理和练耳互动练习。','https://www.musictheory.net/'],
 ['NIDCD','Voice and speech resources','发声、语音、嗓音健康的权威科普。','https://www.nidcd.nih.gov/health/voice-speech-and-language'],
 ['AMTA','Music therapy definition','严格音乐治疗定义和职业边界。','https://www.musictherapy.org/about/musictherapy/'],
 ['R. Murray Schafer','The Tuning of the World','声景、声音生态与世界如何被听见。','https://en.wikipedia.org/wiki/The_Tuning_of_the_World']
];

function layout(content){
  document.body.classList.toggle('compact',state.compact); document.body.classList.toggle('lowMotion',state.lowMotion); document.body.classList.toggle('langEN',state.lang==='EN'); document.body.classList.toggle('langZH',state.lang==='ZH');
  const sideNav=[...nav,...extraNav].map(n=>`<button class="${state.view===n.id?'active':''}" onclick="setView('${n.id}')"><span>${n.ico}</span><span>${t(n.cn,n.en)}</span></button>`).join('');
  const bottom=nav.map(n=>`<button class="${state.view===n.id?'active':''}" onclick="setView('${n.id}')"><span>${n.ico}</span><span>${t(n.cn,n.en)}</span></button>`).join('');
  return `<a class="skip" href="#main">${t('跳到主要内容','Skip to content')}</a><div class="shell"><aside class="side"><div class="brand"><div class="brandMark">∿</div><div><h1>Musicalife</h1><small>${t('音乐知识海洋','Ocean of music knowledge')}</small></div></div><nav class="nav">${sideNav}</nav><div class="sideTools"><button class="pillBtn" onclick="toggleLang()">🌐 ${state.lang==='ZH'?'English':'中文'}</button><button class="pillBtn" onclick="toggleCompact()">${state.compact?'📖 深知识':'◒ 少字模式'}</button><button class="pillBtn" onclick="toggleMotion()">${state.lowMotion?'✦ 动画开':'☽ 低动效'}</button></div></aside><main class="main" id="main"><div class="topbar"><div class="breadcrumbs"><button class="crumb" onclick="setView('home')">🏠 ${t('首页','Home')}</button><span class="crumb">${t('当前','Now')}: ${t((nav.concat(extraNav).find(x=>x.id===state.view)||{}).cn||'首页',(nav.concat(extraNav).find(x=>x.id===state.view)||{}).en||'Home')}</span></div><div class="breadcrumbs"><button class="crumb" onclick="toggleLang()">${state.lang==='ZH'?'EN':'中'}</button><button class="crumb" onclick="toggleCompact()">${state.compact?t('深','Deep'):t('少字','Compact')}</button></div></div>${content}</main></div><nav class="bottomNav">${bottom}</nav><div class="modal" id="modal"></div>`;
}
function toggleLang(){state.lang=state.lang==='ZH'?'EN':'ZH'; save(); render();}
function toggleCompact(){state.compact=!state.compact; save(); render();}
function toggleMotion(){state.lowMotion=!state.lowMotion; save(); render();}

function render(){
  state.view=location.hash.replace('#','')||state.view||'home';
  let content='';
  if(state.view==='home') content=home();
  else if(state.view==='game') content=game();
  else if(state.view==='map') content=mapPage();
  else if(state.view==='voice') content=voicePage();
  else if(state.view==='life') content=lifePage();
  else if(state.view==='world') content=worldPage();
  else if(state.view==='physics') content=physicsPage();
  else if(state.view==='library') content=libraryPage();
  $('#app').innerHTML= state.view==='home'? content : layout(content);
  startCanvases(); updateXP();
}

function home(){return `<section class="hero"><div class="portal"><div class="formulaStage"><canvas data-anim="portal"></canvas></div><h1 class="title">Musicalife｜音乐如何改善生活</h1><p class="subtitle">${t('一个探索音乐趣味的可视化平台：从声波、乐理、发声、身体、大脑、语言、乐器到未来音乐，乘坐知识的小船去感受音乐的秩序、和谐与想象。','A visual voyage into music: waves, theory, voice, body, brain, language, instruments, and future sound — a boat across the ocean of harmony.')}</p><p class="poem deepOnly">${t('音乐不只是声音。它是周期、比例、呼吸、记忆、语言、社会与宇宙想象的交汇；像公式一样准确，也像神话一样召唤我们靠近。','Music is not only sound. It is rhythm, ratio, breath, memory, language, society and cosmic imagination — as exact as a formula, as inviting as a myth.')}</p><div class="ctaRow"><button class="primary" onclick="setView('game')">⛵ ${t('开始声之塔','Start the Odyssey')}</button><button class="secondary" onclick="setView('map')">✧ ${t('打开知识地图','Open knowledge map')}</button><button class="secondary" onclick="setView('voice')">◌ ${t('进入声乐实验室','Voice lab')}</button><button class="secondary" onclick="setView('physics')">∿ ${t('音乐里的数学','Math of music')}</button></div><div class="kpi" style="margin-top:20px"><div><strong>70+</strong><span>${t('专业名词','terms')}</span></div><div><strong>26</strong><span>${t('互动动画','animations')}</span></div><div><strong>12</strong><span>${t('声乐章节','voice chapters')}</span></div><div><strong>10</strong><span>${t('生活场景','life cases')}</span></div></div><p class="small" style="margin-top:18px">${t('小红书：云心｜ID：starcove','Xiaohongshu: 云心｜ID: starcove')}</p></div></section>`}
function pageTitle(cn,en,descCn,descEn){return `<section class="panel"><div class="pageTitle"><div><h2>${t(cn,en)}</h2><p>${t(descCn,descEn)}</p></div></div></section>`}
function game(){const levels=[
 ['sound','∿','声音从哪里来？','Where does sound begin?','wave','理解频率、振幅、相位。'],['tone','◇','为什么同一个音有不同颜色？','Why does one note have color?','harmonics','叠加谐波，看音色诞生。'],['resonance','◌','乐器与身体如何放大声音？','How do bodies resonate?','resonance','共振、驻波、声道滤波。'],['ear','☊','耳朵如何选择声音？','How does the ear choose?','masking','掩蔽、临界带、双耳效应。'],['theory','△','音乐如何变成秩序？','How does music become order?','pitchStair','音阶、音程、和弦、调式。'],['rhythm','⌁','节奏如何启动身体？','How does rhythm move us?','metronome','BPM、细分、切分、夹带。'],['voice','◌','人声是一件乐器','The voice is an instrument','vocalFold','气流、声带、共鸣、元音。'],['language','⌘','讲话也是音乐','Speech is music too','toneContour','声调、重音、停顿、语气。'],['life','☾','音乐如何进入生活？','Music in daily life','multisensory','睡眠、专注、疼痛、情绪。'],['world','∞','世界与未来的声音','World and future sound','theremin','会说话的鼓、电子乐器、太空音乐。']
];return pageTitle('声之塔｜Music Odyssey','Music Odyssey','像解码一座异世界的塔：每一层学习一个音乐法则，用动画和小练习把知识点亮。','Decode music like a mythic tower: each level reveals a law of sound through animation and practice.')+`<section class="panel"><div class="xpBar"><span style="width:${Math.min(100,state.xp)}%"></span></div><p class="small">XP ${state.xp}/100 · ${t('点击关卡完成练习，进度会保存在本机。','Tap levels to complete small quests. Progress is saved locally.')}</p>${levels.map((l,i)=>`<div class="level"><div class="orb">${l[1]}</div><div><h3>${t(l[2],l[3])}</h3><p>${t(l[5],l[5])}</p><canvas class="miniCanvas" data-anim="${l[4]}"></canvas></div><button class="primary" onclick="completeLevel('${l[0]}','${l[4]}')">${state.done[l[0]]?'✓ '+t('已点亮','Done'):t('探索','Explore')}</button></div>`).join('')}</section>`}
function completeLevel(id,anim){ if(!state.done[id]){state.done[id]=true; state.xp=Math.min(100,(state.xp||0)+10); save();} openAnimation(anim); render(); }
function updateXP(){}
function mapPage(){return pageTitle('知识地图｜专业名词连接图','Knowledge map','点击专业名词，查看它和其他概念如何连接：声音物理、听觉心理、乐理数理、声乐人体、脑科学、生活应用、语言文化与未来音乐。','Click any term to see how music concepts connect across sound physics, ear, theory, voice, brain, life, culture and future music.')+`<section class="panel twoCol"><div class="graphWrap"><div class="graphBar"><input id="termSearch" placeholder="${t('搜索：共振、声带、节拍器、调值、双耳效应…','Search: resonance, vocal folds, metronome, tone contour…')}" oninput="drawGraph(this.value)"><button class="secondary" onclick="drawGraph('')">${t('重置','Reset')}</button></div><svg id="graph" class="graphSvg" viewBox="0 0 1050 820" preserveAspectRatio="xMidYMid meet"></svg></div><div id="termDetail" class="detailDrawer">${termDetail(state.selectedTerm||'resonance')}</div></section>`}
function drawGraph(q=''){const svg=$('#graph'); if(!svg)return; q=q.toLowerCase(); let visible=terms.filter(n=>!q||n.cn.toLowerCase().includes(q)||n.en.toLowerCase().includes(q)||n.id.includes(q)); let ids=new Set(visible.map(n=>n.id)); let edges=[]; visible.forEach(n=>(n.rel||[]).forEach(r=>{if(ids.has(r))edges.push([n.id,r])})); const color=id=>categories[termMap[id]?.cat]?.color||'#fff'; let html=`<defs><filter id="glow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>`; edges.forEach(([a,b])=>{let A=termMap[a],B=termMap[b]; html+=`<line class="edge ${(state.selectedTerm===a||state.selectedTerm===b)?'highlight':''}" x1="${A.x}" y1="${A.y}" x2="${B.x}" y2="${B.y}"/>`}); visible.forEach(n=>{let selected=state.selectedTerm===n.id; html+=`<g class="node" onclick="selectTerm('${n.id}')" filter="${selected?'url(#glow)':''}"><circle cx="${n.x}" cy="${n.y}" r="${selected?24:18}" fill="${color(n.id)}" opacity="${selected?'.95':'.72'}"/><text x="${n.x}" y="${n.y+36}" text-anchor="middle">${state.lang==='EN'?n.en:n.cn}</text></g>`}); svg.innerHTML=html;}
function selectTerm(id){state.selectedTerm=id; $('#termDetail').innerHTML=termDetail(id); drawGraph($('#termSearch')?.value||'');}
function termDetail(id){const n=termMap[id]||terms[0], c=categories[n.cat]; return `<h3><span style="color:${c.color}">●</span> ${t(n.cn,n.en)}</h3><p>${state.lang==='EN'? (n.en+' · '+n.short) : n.short}</p><p class="deepOnly">${n.deep}</p><div>${(n.rel||[]).map(r=>`<button class="tag" onclick="selectTerm('${r}')">${t(termMap[r]?.cn||r,termMap[r]?.en||r)}</button>`).join('')}</div><div class="sourceLinks">${(n.links||[]).map(x=>{let [name,url]=x.split('|'); return `<a target="_blank" rel="noopener" href="${url}">${name}</a>`}).join('')}</div><button class="primary" style="margin-top:14px" onclick="openAnimation('${n.anim||'wave'}')">✦ ${t('查看动画','View animation')}</button>`}
function voicePage(){return pageTitle('声乐实验室｜从说话到唱歌','Voice lab','把人声拆成可看见的系统：气流、声带、共鸣、元音、吐字、音准、节奏、和声与健康。','A visible system of voice: airflow, folds, resonance, vowels, articulation, pitch, rhythm, harmony and health.')+`<section class="panel"><div class="chapterNav">${voiceChapters.map(ch=>`<button class="${state.chapter===ch.id?'active':''}" onclick="state.chapter='${ch.id}'; render()">${t(ch.cn,ch.en)}</button>`).join('')}</div>${voiceChapter(voiceChapters.find(x=>x.id===state.chapter)||voiceChapters[0])}</section>`}
function voiceChapter(ch){return `<div class="twoCol"><div><h3>${t(ch.cn,ch.en)}</h3>${ch.body.map(p=>`<p>${p}</p>`).join('')}<div class="deepOnly"><h4>${t('操作练习','Practice')}</h4>${ch.practice.map((p,i)=>`<div class="step"><span class="num">${i+1}</span><span>${p}</span></div>`).join('')}</div><button class="primary" onclick="openAnimation('${ch.anim}')">${t('播放原理动画','Play animation')}</button></div><div><canvas class="bigCanvas" data-anim="${ch.anim}"></canvas></div></div>`}
function lifePage(){return pageTitle('生活声音工具箱','Life sound toolbox','每个生活问题都是卡片：先看少字版，点击后展开机制、步骤、避免事项与资料链接。','Each life problem is a card: compact answer first, then mechanisms, steps, cautions and sources.')+`<section class="panel"><div class="grid">${lifeCards.map((c,i)=>`<details class="accordion card cat-life" style="grid-column:span 6"><summary>${t(c.cn,c.en)} <span>⌄</span></summary><div class="inner"><canvas class="miniCanvas" data-anim="${c.anim}"></canvas><p><b>${t('问题','Problem')}：</b>${c.problem}</p><p><b>${t('机制','Mechanism')}：</b>${c.mechanism}</p>${c.steps.map((s,j)=>`<div class="step"><span class="num">${j+1}</span><span>${s}</span></div>`).join('')}<p><b>${t('避免','Avoid')}：</b>${c.avoid}</p><div class="sourceLinks">${c.links.map(l=>{let [n,u]=l.split('|');return `<a href="${u}" target="_blank" rel="noopener">${n}</a>`}).join('')}</div></div></details>`).join('')}</div></section>`}
function physicsPage(){return pageTitle('音乐里的数学｜Math of Music','Math of Music','用函数、比例、周期、频谱、谐波和干涉去看见音乐的美。','See music through functions, ratios, periods, spectra, harmonics and interference.')+`<section class="panel"><div class="viewTabs">${anims.slice(0,16).map(a=>`<button class="${state.selectedAnim===a[0]?'active':''}" onclick="state.selectedAnim='${a[0]}'; render()">${t(a[1],a[2])}</button>`).join('')}</div><div class="twoCol"><div><canvas class="bigCanvas" data-anim="${state.selectedAnim}"></canvas><div class="controls" id="animControls"></div></div><div>${mathText(state.selectedAnim)}</div></div></section><section class="panel"><h3>${t('关键公式像诗一样简洁','Key formulas')}</h3><div class="grid"><div class="card cat-physics"><h3>f = 1 / T</h3><p>${t('频率和周期互为倒数。节奏、波、呼吸都可以用周期理解。','Frequency and period are reciprocal.')}</p></div><div class="card cat-theory"><h3>2 : 1</h3><p>${t('八度的频率比约为 2:1。A4 440 Hz 到 A5 880 Hz。','An octave is roughly a 2:1 frequency ratio.')}</p></div><div class="card cat-theory"><h3>2^(1/12)</h3><p>${t('十二平均律中，每个半音的频率比例相同。','In 12-TET, every semitone uses the same ratio.')}</p></div><div class="card cat-physics"><h3>f, 2f, 3f...</h3><p>${t('谐波是基频整数倍，它们叠出音色。','Harmonics are integer multiples shaping timbre.')}</p></div></div></section>`}
function mathText(anim){const x={wave:['声波函数','拖动频率和振幅，就能看到“高低”和“强弱”的物理根。'],harmonics:['谐波叠加','一个音不是一条线，而是一组比例。音色来自这些比例的能量分布。'],resonance:['共振','当频率匹配空间/物体的自然响应，声音会被放大。'],fourier:['傅里叶','复杂声音可以转译成许多频率柱，这就是音乐和数学相遇的地方。'],masking:['掩蔽','噪声不是只会伤害，也可以作为工具：稳定地覆盖不可预测声音。'],binaural:['双耳','左右耳的时间差和强度差让空间出现。'],anc:['反相抵消','当波形相反时，部分能量会抵消。'],pitchStair:['音阶','音阶是频率空间中的路径。半音是最小台阶，八度是一座桥。'],metronome:['节拍器','节拍器是一列周期脉冲；真正目标是形成身体内部时钟。'],syncopation:['切分','重音位置偏移，让预测系统被轻轻挑战。'],polyrhythm:['复节奏','两个时间网格叠在一起，像拓扑里的路径交叉。'],chord:['和弦','多个频率同时存在，简单比例更稳定，复杂关系更紧张。']};let [h,p]=x[anim]||x.wave; return `<h3>${h}</h3><p>${p}</p><p class="deepOnly">${t('把每个动画当作一个翻译器：物理量 → 听觉感受 → 音乐结构 → 生活使用。','Use each animation as a translator: physical quantity → perception → music structure → life practice.')}</p><button class="primary" onclick="openAnimation('${anim}')">${t('放大查看','Open large')}</button>`}
function worldPage(){return pageTitle('世界音乐博物馆｜声音、语言、乐器与未来','World music museum','按发声原理、语言文化和媒介史探索音乐：古老乐器、电子乐器、无接触乐器、会说话的鼓、太空音乐。','Explore music by sound-making principle, language, culture and media history.')+`<section class="panel"><h3>${t('奇妙乐器馆','Instrument zoo')}</h3><div class="grid">${instruments.map(x=>`<div class="card cat-world"><h3>${x[0]} <small>${x[1]}</small></h3><span class="tag">${t(x[2],x[3])}</span><p>${x[4]}</p><button class="secondary" onclick="openAnimation('${x[5]}')">${t('看原理动画','Animation')}</button></div>`).join('')}</div></section><section class="panel"><h3>${t('音乐媒介发展史','History of music media')}</h3><div class="timeline">${timeline.map((x,i)=>`<div class="timeCard"><strong>${i+1}. ${t(x[0],x[1])}</strong><p>${x[2]}</p></div>`).join('')}</div></section><section class="panel"><h3>${t('语言、社会与音乐','Language, society and music')}</h3><div class="grid"><div class="card cat-world"><h3>${t('语言声调','Tone languages')}</h3><p>${t('汉语、粤语、泰语、越南语、约鲁巴语等语言提醒我们：讲话本身就有旋律结构。','Tone languages remind us that speech itself has melodic structure.')}</p><button onclick="selectAndMap('languageTone')" class="secondary">${t('去地图','Map')}</button></div><div class="card cat-world"><h3>${t('合唱与社会同步','Choir and social synchrony')}</h3><p>${t('一起唱不是声音叠加那么简单，而是呼吸、节奏、注意和归属感的同步。','Singing together synchronizes breath, timing, attention and belonging.')}</p><button onclick="openAnimation('choir')" class="secondary">${t('看合唱动画','Choir')}</button></div><div class="card cat-life"><h3>${t('公共音乐与声音权利','Sound rights')}</h3><p>${t('声景设计要问：谁能控制声音？谁有静音权？谁被噪声排除？','Soundscape design asks who controls sound, who has silence, and who is excluded by noise.')}</p><button onclick="selectAndMap('soundscape')" class="secondary">${t('查看声景','Soundscape')}</button></div></div></section>`}
function libraryPage(){return pageTitle('资料图书馆','Library','可查证的书籍、课程、论文和平台链接。网页中每个专业名词都应能通向这里。','Verifiable books, courses, papers and platforms. Every term should lead here.')+`<section class="panel"><div class="grid">${books.map(b=>`<div class="card cat-brain"><h3>${b[0]}</h3><p><b>${b[1]}</b></p><p>${b[2]}</p><a class="secondary" href="${b[3]}" target="_blank" rel="noopener">${t('打开来源','Open source')}</a></div>`).join('')}</div></section><section class="panel"><h3>${t('音乐平台搜索','Music platform search')}</h3><p>${t('推荐不要只给固定曲目，而是给“听觉路线 + 平台搜索”：Bilibili、YouTube、Spotify、Apple Music、网易云、QQ音乐、Bandcamp、IMSLP。','Use listening routes plus platform search: Bilibili, YouTube, Spotify, Apple Music, NetEase, QQ Music, Bandcamp, IMSLP.')}</p><div class="sourceLinks">${['Satie Gymnopédies','Debussy piano','Brian Eno ambient','Max Richter sleep','Nils Frahm','Arvo Pärt Spiegel im Spiegel','West African talking drum','Theremin performance'].map(q=>`<a target="_blank" rel="noopener" href="https://www.bilibili.com/search?keyword=${encodeURIComponent(q)}">Bilibili: ${q}</a>`).join('')}</div></section>`}
function selectAndMap(id){state.selectedTerm=id; setView('map'); setTimeout(()=>drawGraph(''),50)}

function openAnimation(type){state.selectedAnim=type; const m=$('#modal')||document.createElement('div'); m.id='modal'; m.className='modal show'; m.innerHTML=`<div class="modalBox"><div class="modalHead"><h3>${(anims.find(a=>a[0]===type)||['',type,type])[state.lang==='EN'?2:1]}</h3><button class="closeBtn" onclick="closeModal()">✕</button></div><canvas class="bigCanvas" data-anim="${type}"></canvas><div id="modalControls" class="controls"></div><p class="small">${t('提示：这个动画是概念模型，不是医学诊断或治疗工具。','This is a conceptual model, not a medical diagnostic or treatment tool.')}</p></div>`; document.body.appendChild(m); startCanvases();}
function closeModal(){const m=$('#modal'); if(m)m.classList.remove('show')}

function startCanvases(){
  $$('.miniCanvas,.bigCanvas,#cosmos canvas,.formulaStage canvas,canvas[data-anim]').forEach(c=>{if(c.dataset.running)return; c.dataset.running='1'; setupCanvas(c); animateCanvas(c);});
  if(state.view==='map') setTimeout(()=>drawGraph(''),0);
}
function setupCanvas(c){const r=c.getBoundingClientRect(); const d=window.devicePixelRatio||1; c.width=Math.max(320,Math.floor(r.width*d)); c.height=Math.max(160,Math.floor((r.height||240)*d)); c._d=d; c._params={freq:3,amp:.6,harm:5,bpm:80,closure:.55,air:.55,vowel:'a'};}
function animateCanvas(c){const ctx=c.getContext('2d'); const type=c.dataset.anim||'wave'; const loop=(time)=>{if(!document.body.contains(c))return; draw(ctx,c,type,time/1000,c._params||{}); if(!state.lowMotion) requestAnimationFrame(loop);}; requestAnimationFrame(loop);}
function bg(ctx,w,h){const g=ctx.createLinearGradient(0,0,w,h); g.addColorStop(0,'#090722'); g.addColorStop(.5,'#17104a'); g.addColorStop(1,'#07172b'); ctx.fillStyle=g; ctx.fillRect(0,0,w,h); ctx.strokeStyle='rgba(255,255,255,.08)'; ctx.lineWidth=1; for(let i=0;i<8;i++){ctx.beginPath(); ctx.moveTo(0,h*i/8); ctx.lineTo(w,h*i/8); ctx.stroke();}}
function draw(ctx,c,type,t,p){const w=c.width,h=c.height,d=c._d||1; ctx.save(); bg(ctx,w,h); ctx.scale(d,d); const W=w/d,H=h/d; const line=(color='#74d7ff',lw=2)=>{ctx.strokeStyle=color;ctx.lineWidth=lw;ctx.lineCap='round';ctx.lineJoin='round'}; const text=(s,x,y,size=14,color='rgba(255,255,255,.86)')=>{ctx.fillStyle=color;ctx.font=`${size}px ${getComputedStyle(document.body).fontFamily}`;ctx.fillText(s,x,y)}; const cx=W/2,cy=H/2;
  if(type==='portal'){line('#bdeaff',2); for(let k=0;k<5;k++){ctx.beginPath(); for(let x=0;x<W;x++){let y=cy+Math.sin(x*.018+t*1.6+k)*34*Math.cos(k*.7)+Math.cos(x*.006+k+t)*20; if(x===0)ctx.moveTo(x,y); else ctx.lineTo(x,y);} ctx.globalAlpha=.26+k*.11; ctx.stroke();} ctx.globalAlpha=1; text('y = Σ Aₙ sin(2π fₙ t + φₙ)',24,38,18,'#f6d98b'); text('music as function · breath as rhythm · world as resonance',24,H-28,14,'#c7c1df');}
  else if(type==='wave'){let freq=p.freq||3, amp=(p.amp||.6)*H*.32; line('#74d7ff',3); ctx.beginPath(); for(let x=0;x<W;x++){let y=cy+Math.sin((x/W*freq*2*Math.PI)+t*2)*amp; if(x===0)ctx.moveTo(x,y); else ctx.lineTo(x,y);} ctx.stroke(); text('frequency ↔ pitch',18,28); text('amplitude ↔ loudness',18,50,'14','#f6d98b');}
  else if(type==='harmonics'||type==='fourier'){let n=type==='fourier'?10:6; line('#ff91d0',2); ctx.beginPath(); for(let x=0;x<W;x++){let y=cy, xx=x/W*2*Math.PI; for(let k=1;k<=n;k++) y+=Math.sin(xx*k+t*(.5+k*.05))*H*.12/k; if(x===0)ctx.moveTo(x,y); else ctx.lineTo(x,y);} ctx.stroke(); for(let k=1;k<=n;k++){let bh=H*.35/k; ctx.fillStyle=`rgba(116,215,255,${.25+.05*k})`; ctx.fillRect(30+k*(W-80)/n,H-30-bh,12,bh);} text('f + 2f + 3f + ... = timbre',18,30,'15','#f6d98b');}
  else if(type==='resonance'||type==='chambers'){ctx.fillStyle='rgba(255,255,255,.09)'; ctx.beginPath(); ctx.roundRect(40,cy-40,W-80,80,35); ctx.fill(); line('#f6d98b',3); for(let k=1;k<=4;k++){ctx.beginPath(); for(let x=55;x<W-55;x++){let y=cy+Math.sin((x-55)/(W-110)*Math.PI*k)*28*Math.sin(t*1.2+k); if(x===55)ctx.moveTo(x,y); else ctx.lineTo(x,y);} ctx.stroke();} text(type==='chambers'?'voice tract: pharynx · mouth · nasal path':'resonant tube amplifies selected frequencies',18,30);}
  else if(type==='masking'){for(let i=0;i<200;i++){ctx.fillStyle=`rgba(180,210,255,${Math.random()*.08})`; ctx.fillRect(Math.random()*W,Math.random()*H,2,2)} line('#f6d98b',3); ctx.beginPath(); for(let x=0;x<W;x++){let y=cy+Math.sin(x*.08+t*5)*18; if(x===0)ctx.moveTo(x,y); else ctx.lineTo(x,y)} ctx.stroke(); ctx.fillStyle='rgba(116,215,255,.22)'; ctx.fillRect(W*.15,cy-70,W*.7,140); text('stable noise can cover unpredictable sound',18,30);}
  else if(type==='binaural'||type==='binauralBeat'){ctx.fillStyle='rgba(255,255,255,.11)'; ctx.beginPath(); ctx.arc(W*.25,cy,34,0,7); ctx.arc(W*.75,cy,34,0,7); ctx.fill(); line('#74d7ff',2); for(let side of [.25,.75]){ctx.beginPath(); for(let x=0;x<W;x++){let y=cy+(side-.5)*90+Math.sin(x*.06+t*(type==='binauralBeat'?4.3:3)+(side*10))*18; if(x===0)ctx.moveTo(x,y); else ctx.lineTo(x,y)} ctx.stroke();} text(type==='binauralBeat'?'two close frequencies → perceived beat':'left/right time + level differences → space',18,30);}
  else if(type==='anc'){line('rgba(116,215,255,.8)',2); ctx.beginPath(); for(let x=0;x<W;x++){let y=cy+Math.sin(x*.035+t*3)*42; if(x===0)ctx.moveTo(x,y); else ctx.lineTo(x,y)} ctx.stroke(); line('rgba(255,145,208,.8)',2); ctx.beginPath(); for(let x=0;x<W;x++){let y=cy-Math.sin(x*.035+t*3)*38; if(x===0)ctx.moveTo(x,y); else ctx.lineTo(x,y)} ctx.stroke(); line('#f6d98b',3); ctx.beginPath(); for(let x=0;x<W;x++){let y=cy+Math.sin(x*.035+t*3)*4; if(x===0)ctx.moveTo(x,y); else ctx.lineTo(x,y)} ctx.stroke(); text('noise + anti-noise ≈ less low-frequency rumble',18,30);}
  else if(type==='pitchStair'||type==='temperament'||type==='earTraining'){let steps=12; for(let i=0;i<steps;i++){let x=30+i*(W-60)/steps,y=H-40-i*(H-90)/steps; ctx.fillStyle=i%2?'rgba(166,140,255,.24)':'rgba(246,217,139,.2)'; ctx.fillRect(x,y,(W-65)/steps,24); text(i===0?'do':i===4?'mi':i===7?'sol':i===11?'ti':'',x+3,y+17,12)} line('#74d7ff',2); ctx.beginPath(); for(let i=0;i<steps;i++){let x=30+i*(W-60)/steps,y=H-28-i*(H-90)/steps; if(i===0)ctx.moveTo(x,y); else ctx.lineTo(x,y)} ctx.stroke(); text('semitones → scale → relative pitch',18,30);}
  else if(type==='metronome'||type==='syncopation'||type==='polyrhythm'){let bpm=p.bpm||80, beat=(t*bpm/60)%4; for(let i=0;i<4;i++){ctx.fillStyle=i<beat?'#f6d98b':'rgba(255,255,255,.12)'; ctx.beginPath(); ctx.arc(60+i*(W-120)/3,cy,22+(i===Math.floor(beat)?8:0),0,7); ctx.fill();} if(type==='polyrhythm'){for(let i=0;i<3;i++){ctx.fillStyle='rgba(116,215,255,.65)'; ctx.beginPath(); ctx.arc(80+i*(W-160)/2,cy+60,14,0,7); ctx.fill();}} if(type==='syncopation'){ctx.fillStyle='rgba(255,145,208,.75)'; ctx.beginPath(); ctx.arc(60+((beat+.5)%4)*(W-120)/3,cy-55,14,0,7); ctx.fill();} text(type==='polyrhythm'?'3 over 4: time grids crossing':type==='syncopation'?'syncopation: accent displaced':'BPM: periodic pulse + internal clock',18,30);}
  else if(type==='chord'||type==='harmony'||type==='choir'){let ys=[cy+50,cy,cy-50,cy-85], colors=['#74d7ff','#f6d98b','#ff91d0','#9ff3c8']; ys.forEach((y,i)=>{line(colors[i],2); ctx.beginPath(); for(let x=20;x<W-20;x++){let yy=y+Math.sin(x*.02*(i+1)+t*2)*10; if(x===20)ctx.moveTo(x,yy); else ctx.lineTo(x,yy)} ctx.stroke(); text(['do','mi','sol','ti'][i]||'',W-45,y+5,14,colors[i]);}); text('voices become harmony when frequencies relate',18,30);}
  else if(type==='vocalFold'){let air=(Math.sin(t*3)+1)/2; ctx.fillStyle='rgba(116,215,255,.15)'; for(let i=0;i<8;i++){ctx.beginPath();ctx.arc(W*.2+i*W*.08,H-40-air*90,5,0,7);ctx.fill()} ctx.fillStyle='#ff91d0'; ctx.beginPath(); ctx.ellipse(cx-18,cy,18,70,Math.sin(t*8)*.08,0,7); ctx.ellipse(cx+18,cy,18,70,-Math.sin(t*8)*.08,0,7); ctx.fill(); line('#f6d98b',2); ctx.beginPath(); ctx.moveTo(cx,cy-70); ctx.lineTo(cx,cy+70); ctx.stroke(); text('airflow + fold vibration = voice source',18,30);}
  else if(type==='sovt'){ctx.fillStyle='rgba(255,145,208,.35)'; ctx.fillRect(W*.22,cy-24,W*.34,48); ctx.fillStyle='rgba(116,215,255,.25)'; ctx.fillRect(W*.55,cy-8,W*.28,16); line('#f6d98b',2); for(let i=0;i<7;i++){ctx.beginPath();ctx.arc(W*.38,cy,18+i*12+t%1*12,0,7);ctx.stroke()} text('semi-closed outlet creates helpful back pressure',18,30);}
  else if(type==='formant'){let vowels=['i','e','a','o','u']; vowels.forEach((v,i)=>{let x=50+i*(W-100)/4; ctx.fillStyle='rgba(255,255,255,.10)'; ctx.beginPath();ctx.ellipse(x,cy,22+i*4,50-i*5,0,0,7);ctx.fill(); text(v,x-4,cy+75,18,'#f6d98b');}); line('#74d7ff',2); ctx.beginPath(); for(let x=0;x<W;x++){let y=H-45-(Math.sin(x*.03+t)+1)*20-(Math.sin(x*.08+t*1.2)+1)*25; if(x===0)ctx.moveTo(x,y); else ctx.lineTo(x,y)} ctx.stroke(); text('vowel = vocal tract filter shape',18,30);}
  else if(type==='toneContour'||type==='prosody'){let contours=[[0,0],[0,1],[1,.2,.7],[1,0]]; contours.forEach((arr,i)=>{let x0=40+i*(W-80)/4, ww=(W-110)/4; line(['#f6d98b','#74d7ff','#ff91d0','#9ff3c8'][i],3); ctx.beginPath(); for(let x=0;x<ww;x++){let u=x/ww; let val=i===0?.22:i===1?1-u:i===2?(u<.55?.75+u*.25:.9-(u-.55)*1.5):u; let y=H-50-val*(H-90); if(x===0)ctx.moveTo(x0+x,y); else ctx.lineTo(x0+x,y)} ctx.stroke(); text(['1','2','3','4'][i],x0+ww/2,H-22,16);}); text('tone contour: language as melody',18,30);}
  else if(type==='multisensory'||type==='mindfulness'||type==='painGate'){['sound','breath','heart','attention'].forEach((s,i)=>{let r=22+Math.sin(t*1.5+i)*8; ctx.fillStyle=['rgba(116,215,255,.55)','rgba(159,243,200,.45)','rgba(255,145,208,.45)','rgba(246,217,139,.45)'][i]; ctx.beginPath();ctx.arc(W*(.2+i*.2),cy,r,0,7);ctx.fill(); text(s,W*(.2+i*.2)-22,cy+58,12)}); line('#fff',1.5); ctx.beginPath();ctx.moveTo(W*.2,cy);ctx.bezierCurveTo(W*.35,cy-80,W*.55,cy+80,W*.8,cy);ctx.stroke(); text('synchronizing sound · breath · body · attention',18,30);}
  else if(type==='painGate'){text('attention can turn toward rhythm, breath, image',18,30)}
  else if(type==='soundscape'){let rooms=[['danger','#ff9c9c'],['background','#74d7ff'],['anchor','#f6d98b'],['silence','#9ff3c8']]; rooms.forEach((r,i)=>{ctx.fillStyle=r[1]+'44'; ctx.fillRect(30+i*(W-60)/4,80,(W-80)/4,H-140); text(r[0],38+i*(W-60)/4,105,13)}); text('design sound layers + control + exit',18,30);}
  else if(type==='talkingDrum'){line('#f6d98b',3); ctx.beginPath(); for(let x=0;x<W;x++){let y=cy+Math.sin(x*.03+t*4)*25*(1+.6*Math.sin(x*.012+t)); if(x===0)ctx.moveTo(x,y); else ctx.lineTo(x,y)} ctx.stroke(); text('drum imitates tone contour + rhythm of speech',18,30);}
  else if(type==='theremin'){ctx.fillStyle='rgba(116,215,255,.25)'; ctx.fillRect(W*.47,70,12,H-120); let handX=W*(.5+.32*Math.sin(t)); ctx.fillStyle='#f6d98b'; ctx.beginPath(); ctx.arc(handX,cy,22,0,7);ctx.fill(); line('#74d7ff',2); for(let i=1;i<5;i++){ctx.beginPath();ctx.arc(W*.5,cy,Math.abs(handX-W*.5)+i*18,0,7);ctx.stroke()} text('distance of hand → frequency / volume',18,30);}
  else if(type==='sampler'){for(let i=0;i<12;i++){ctx.fillStyle=i%3?'rgba(116,215,255,.3)':'rgba(255,145,208,.35)';ctx.fillRect(30+i*(W-60)/12,cy-50+Math.sin(i+t)*25,(W-80)/12,100);} text('sample → slice → rearrange → new music',18,30);}
  else if(type==='haptic'){for(let i=0;i<7;i++){ctx.fillStyle=`rgba(246,217,139,${.15+.08*Math.sin(t*3+i)})`;ctx.beginPath();ctx.arc(W*.2+i*W*.1,cy,25+10*Math.sin(t*4+i),0,7);ctx.fill()} text('music translated into touch vibration',18,30);}
  else {text(type,18,30)}
  ctx.restore();}

function drawCosmos(){const c=$('#cosmos'); if(!c)return; const ctx=c.getContext('2d'); const resize=()=>{c.width=innerWidth*(devicePixelRatio||1); c.height=innerHeight*(devicePixelRatio||1)}; resize(); addEventListener('resize',resize); let stars=Array.from({length:120},()=>[Math.random(),Math.random(),Math.random()*2]); const loop=(t)=>{let W=c.width,H=c.height; ctx.clearRect(0,0,W,H); let g=ctx.createRadialGradient(W*.5,H*.35,0,W*.5,H*.35,Math.max(W,H)*.8); g.addColorStop(0,'rgba(116,215,255,.08)'); g.addColorStop(.5,'rgba(166,140,255,.05)'); g.addColorStop(1,'rgba(0,0,0,0)'); ctx.fillStyle=g; ctx.fillRect(0,0,W,H); ctx.fillStyle='rgba(255,255,255,.7)'; stars.forEach(s=>{ctx.globalAlpha=.18+.7*Math.sin(t*.001+s[2]*3)**2; ctx.beginPath(); ctx.arc(s[0]*W,s[1]*H,s[2]*(devicePixelRatio||1),0,7); ctx.fill();}); ctx.globalAlpha=1; if(!state.lowMotion)requestAnimationFrame(loop)}; requestAnimationFrame(loop)}

document.addEventListener('click',e=>{if(e.target.classList.contains('modal')) closeModal()});
window.selectTerm=selectTerm; window.drawGraph=drawGraph; window.setView=setView; window.toggleLang=toggleLang; window.toggleCompact=toggleCompact; window.toggleMotion=toggleMotion; window.completeLevel=completeLevel; window.openAnimation=openAnimation; window.closeModal=closeModal; window.selectAndMap=selectAndMap;
drawCosmos(); render();
